// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: orderer/smartbft/configuration.proto

package smartbft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options_Rotation int32

const (
	Options_ROTATION_UNSPECIFIED Options_Rotation = 0
	Options_ROTATION_OFF         Options_Rotation = 1
	Options_ROTATION_ON          Options_Rotation = 2
)

// Enum value maps for Options_Rotation.
var (
	Options_Rotation_name = map[int32]string{
		0: "ROTATION_UNSPECIFIED",
		1: "ROTATION_OFF",
		2: "ROTATION_ON",
	}
	Options_Rotation_value = map[string]int32{
		"ROTATION_UNSPECIFIED": 0,
		"ROTATION_OFF":         1,
		"ROTATION_ON":          2,
	}
)

func (x Options_Rotation) Enum() *Options_Rotation {
	p := new(Options_Rotation)
	*p = x
	return p
}

func (x Options_Rotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Options_Rotation) Descriptor() protoreflect.EnumDescriptor {
	return file_orderer_smartbft_configuration_proto_enumTypes[0].Descriptor()
}

func (Options_Rotation) Type() protoreflect.EnumType {
	return &file_orderer_smartbft_configuration_proto_enumTypes[0]
}

func (x Options_Rotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Options_Rotation.Descriptor instead.
func (Options_Rotation) EnumDescriptor() ([]byte, []int) {
	return file_orderer_smartbft_configuration_proto_rawDescGZIP(), []int{0, 0}
}

// Options to be specified for all the smartbft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RequestBatchMaxCount      uint64                 `protobuf:"varint,1,opt,name=request_batch_max_count,json=requestBatchMaxCount,proto3" json:"request_batch_max_count,omitempty"`
	RequestBatchMaxBytes      uint64                 `protobuf:"varint,2,opt,name=request_batch_max_bytes,json=requestBatchMaxBytes,proto3" json:"request_batch_max_bytes,omitempty"`
	RequestBatchMaxInterval   string                 `protobuf:"bytes,3,opt,name=request_batch_max_interval,json=requestBatchMaxInterval,proto3" json:"request_batch_max_interval,omitempty"`
	IncomingMessageBufferSize uint64                 `protobuf:"varint,4,opt,name=incoming_message_buffer_size,json=incomingMessageBufferSize,proto3" json:"incoming_message_buffer_size,omitempty"`
	RequestPoolSize           uint64                 `protobuf:"varint,5,opt,name=request_pool_size,json=requestPoolSize,proto3" json:"request_pool_size,omitempty"`
	RequestForwardTimeout     string                 `protobuf:"bytes,6,opt,name=request_forward_timeout,json=requestForwardTimeout,proto3" json:"request_forward_timeout,omitempty"`
	RequestComplainTimeout    string                 `protobuf:"bytes,7,opt,name=request_complain_timeout,json=requestComplainTimeout,proto3" json:"request_complain_timeout,omitempty"`
	RequestAutoRemoveTimeout  string                 `protobuf:"bytes,8,opt,name=request_auto_remove_timeout,json=requestAutoRemoveTimeout,proto3" json:"request_auto_remove_timeout,omitempty"`
	RequestMaxBytes           uint64                 `protobuf:"varint,9,opt,name=request_max_bytes,json=requestMaxBytes,proto3" json:"request_max_bytes,omitempty"`
	ViewChangeResendInterval  string                 `protobuf:"bytes,10,opt,name=view_change_resend_interval,json=viewChangeResendInterval,proto3" json:"view_change_resend_interval,omitempty"`
	ViewChangeTimeout         string                 `protobuf:"bytes,11,opt,name=view_change_timeout,json=viewChangeTimeout,proto3" json:"view_change_timeout,omitempty"`
	LeaderHeartbeatTimeout    string                 `protobuf:"bytes,12,opt,name=leader_heartbeat_timeout,json=leaderHeartbeatTimeout,proto3" json:"leader_heartbeat_timeout,omitempty"`
	LeaderHeartbeatCount      uint64                 `protobuf:"varint,13,opt,name=leader_heartbeat_count,json=leaderHeartbeatCount,proto3" json:"leader_heartbeat_count,omitempty"`
	CollectTimeout            string                 `protobuf:"bytes,14,opt,name=collect_timeout,json=collectTimeout,proto3" json:"collect_timeout,omitempty"`
	SyncOnStart               bool                   `protobuf:"varint,15,opt,name=sync_on_start,json=syncOnStart,proto3" json:"sync_on_start,omitempty"`
	SpeedUpViewChange         bool                   `protobuf:"varint,16,opt,name=speed_up_view_change,json=speedUpViewChange,proto3" json:"speed_up_view_change,omitempty"`
	LeaderRotation            Options_Rotation       `protobuf:"varint,17,opt,name=leader_rotation,json=leaderRotation,proto3,enum=orderer.smartbft.Options_Rotation" json:"leader_rotation,omitempty"`
	DecisionsPerLeader        uint64                 `protobuf:"varint,18,opt,name=decisions_per_leader,json=decisionsPerLeader,proto3" json:"decisions_per_leader,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_orderer_smartbft_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_orderer_smartbft_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_orderer_smartbft_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetRequestBatchMaxCount() uint64 {
	if x != nil {
		return x.RequestBatchMaxCount
	}
	return 0
}

func (x *Options) GetRequestBatchMaxBytes() uint64 {
	if x != nil {
		return x.RequestBatchMaxBytes
	}
	return 0
}

func (x *Options) GetRequestBatchMaxInterval() string {
	if x != nil {
		return x.RequestBatchMaxInterval
	}
	return ""
}

func (x *Options) GetIncomingMessageBufferSize() uint64 {
	if x != nil {
		return x.IncomingMessageBufferSize
	}
	return 0
}

func (x *Options) GetRequestPoolSize() uint64 {
	if x != nil {
		return x.RequestPoolSize
	}
	return 0
}

func (x *Options) GetRequestForwardTimeout() string {
	if x != nil {
		return x.RequestForwardTimeout
	}
	return ""
}

func (x *Options) GetRequestComplainTimeout() string {
	if x != nil {
		return x.RequestComplainTimeout
	}
	return ""
}

func (x *Options) GetRequestAutoRemoveTimeout() string {
	if x != nil {
		return x.RequestAutoRemoveTimeout
	}
	return ""
}

func (x *Options) GetRequestMaxBytes() uint64 {
	if x != nil {
		return x.RequestMaxBytes
	}
	return 0
}

func (x *Options) GetViewChangeResendInterval() string {
	if x != nil {
		return x.ViewChangeResendInterval
	}
	return ""
}

func (x *Options) GetViewChangeTimeout() string {
	if x != nil {
		return x.ViewChangeTimeout
	}
	return ""
}

func (x *Options) GetLeaderHeartbeatTimeout() string {
	if x != nil {
		return x.LeaderHeartbeatTimeout
	}
	return ""
}

func (x *Options) GetLeaderHeartbeatCount() uint64 {
	if x != nil {
		return x.LeaderHeartbeatCount
	}
	return 0
}

func (x *Options) GetCollectTimeout() string {
	if x != nil {
		return x.CollectTimeout
	}
	return ""
}

func (x *Options) GetSyncOnStart() bool {
	if x != nil {
		return x.SyncOnStart
	}
	return false
}

func (x *Options) GetSpeedUpViewChange() bool {
	if x != nil {
		return x.SpeedUpViewChange
	}
	return false
}

func (x *Options) GetLeaderRotation() Options_Rotation {
	if x != nil {
		return x.LeaderRotation
	}
	return Options_ROTATION_UNSPECIFIED
}

func (x *Options) GetDecisionsPerLeader() uint64 {
	if x != nil {
		return x.DecisionsPerLeader
	}
	return 0
}

var File_orderer_smartbft_configuration_proto protoreflect.FileDescriptor

const file_orderer_smartbft_configuration_proto_rawDesc = "" +
	"\n" +
	"$orderer/smartbft/configuration.proto\x12\x10orderer.smartbft\"\xa3\b\n" +
	"\aOptions\x125\n" +
	"\x17request_batch_max_count\x18\x01 \x01(\x04R\x14requestBatchMaxCount\x125\n" +
	"\x17request_batch_max_bytes\x18\x02 \x01(\x04R\x14requestBatchMaxBytes\x12;\n" +
	"\x1arequest_batch_max_interval\x18\x03 \x01(\tR\x17requestBatchMaxInterval\x12?\n" +
	"\x1cincoming_message_buffer_size\x18\x04 \x01(\x04R\x19incomingMessageBufferSize\x12*\n" +
	"\x11request_pool_size\x18\x05 \x01(\x04R\x0frequestPoolSize\x126\n" +
	"\x17request_forward_timeout\x18\x06 \x01(\tR\x15requestForwardTimeout\x128\n" +
	"\x18request_complain_timeout\x18\a \x01(\tR\x16requestComplainTimeout\x12=\n" +
	"\x1brequest_auto_remove_timeout\x18\b \x01(\tR\x18requestAutoRemoveTimeout\x12*\n" +
	"\x11request_max_bytes\x18\t \x01(\x04R\x0frequestMaxBytes\x12=\n" +
	"\x1bview_change_resend_interval\x18\n" +
	" \x01(\tR\x18viewChangeResendInterval\x12.\n" +
	"\x13view_change_timeout\x18\v \x01(\tR\x11viewChangeTimeout\x128\n" +
	"\x18leader_heartbeat_timeout\x18\f \x01(\tR\x16leaderHeartbeatTimeout\x124\n" +
	"\x16leader_heartbeat_count\x18\r \x01(\x04R\x14leaderHeartbeatCount\x12'\n" +
	"\x0fcollect_timeout\x18\x0e \x01(\tR\x0ecollectTimeout\x12\"\n" +
	"\rsync_on_start\x18\x0f \x01(\bR\vsyncOnStart\x12/\n" +
	"\x14speed_up_view_change\x18\x10 \x01(\bR\x11speedUpViewChange\x12K\n" +
	"\x0fleader_rotation\x18\x11 \x01(\x0e2\".orderer.smartbft.Options.RotationR\x0eleaderRotation\x120\n" +
	"\x14decisions_per_leader\x18\x12 \x01(\x04R\x12decisionsPerLeader\"G\n" +
	"\bRotation\x12\x18\n" +
	"\x14ROTATION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fROTATION_OFF\x10\x01\x12\x0f\n" +
	"\vROTATION_ON\x10\x02Bj\n" +
	".org.hyperledger.fabric.protos.orderer.smartbftZ8github.com/hyperledger/fabric-protos-go/orderer/smartbftb\x06proto3"

var (
	file_orderer_smartbft_configuration_proto_rawDescOnce sync.Once
	file_orderer_smartbft_configuration_proto_rawDescData []byte
)

func file_orderer_smartbft_configuration_proto_rawDescGZIP() []byte {
	file_orderer_smartbft_configuration_proto_rawDescOnce.Do(func() {
		file_orderer_smartbft_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderer_smartbft_configuration_proto_rawDesc), len(file_orderer_smartbft_configuration_proto_rawDesc)))
	})
	return file_orderer_smartbft_configuration_proto_rawDescData
}

var file_orderer_smartbft_configuration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orderer_smartbft_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_orderer_smartbft_configuration_proto_goTypes = []any{
	(Options_Rotation)(0), // 0: orderer.smartbft.Options.Rotation
	(*Options)(nil),       // 1: orderer.smartbft.Options
}
var file_orderer_smartbft_configuration_proto_depIdxs = []int32{
	0, // 0: orderer.smartbft.Options.leader_rotation:type_name -> orderer.smartbft.Options.Rotation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orderer_smartbft_configuration_proto_init() }
func file_orderer_smartbft_configuration_proto_init() {
	if File_orderer_smartbft_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderer_smartbft_configuration_proto_rawDesc), len(file_orderer_smartbft_configuration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderer_smartbft_configuration_proto_goTypes,
		DependencyIndexes: file_orderer_smartbft_configuration_proto_depIdxs,
		EnumInfos:         file_orderer_smartbft_configuration_proto_enumTypes,
		MessageInfos:      file_orderer_smartbft_configuration_proto_msgTypes,
	}.Build()
	File_orderer_smartbft_configuration_proto = out.File
	file_orderer_smartbft_configuration_proto_goTypes = nil
	file_orderer_smartbft_configuration_proto_depIdxs = nil
}
