// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: msp/identities.proto

package msp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This struct represents an Identity
// (with its MSP identifier) to be used
// to serialize it and deserialize it
type SerializedIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the associated membership service provider
	Mspid string `protobuf:"bytes,1,opt,name=mspid,proto3" json:"mspid,omitempty"`
	// the Identity, serialized according to the rules of its MPS
	IdBytes       []byte `protobuf:"bytes,2,opt,name=id_bytes,json=idBytes,proto3" json:"id_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedIdentity) Reset() {
	*x = SerializedIdentity{}
	mi := &file_msp_identities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedIdentity) ProtoMessage() {}

func (x *SerializedIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_msp_identities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedIdentity.ProtoReflect.Descriptor instead.
func (*SerializedIdentity) Descriptor() ([]byte, []int) {
	return file_msp_identities_proto_rawDescGZIP(), []int{0}
}

func (x *SerializedIdentity) GetMspid() string {
	if x != nil {
		return x.Mspid
	}
	return ""
}

func (x *SerializedIdentity) GetIdBytes() []byte {
	if x != nil {
		return x.IdBytes
	}
	return nil
}

// This struct represents an Idemix Identity
// to be used to serialize it and deserialize it.
// The IdemixMSP will first serialize an idemix identity to bytes using
// this proto, and then uses these bytes as id_bytes in SerializedIdentity
type SerializedIdemixIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nym_x is the X-component of the pseudonym elliptic curve point.
	// It is a []byte representation of an amcl.BIG
	// The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
	NymX []byte `protobuf:"bytes,1,opt,name=nym_x,json=nymX,proto3" json:"nym_x,omitempty"`
	// nym_y is the Y-component of the pseudonym elliptic curve point.
	// It is a []byte representation of an amcl.BIG
	// The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
	NymY []byte `protobuf:"bytes,2,opt,name=nym_y,json=nymY,proto3" json:"nym_y,omitempty"`
	// ou contains the organizational unit of the idemix identity
	Ou []byte `protobuf:"bytes,3,opt,name=ou,proto3" json:"ou,omitempty"`
	// role contains the role of this identity (e.g., ADMIN or MEMBER)
	Role []byte `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// proof contains the cryptographic evidence that this identity is valid
	Proof         []byte `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedIdemixIdentity) Reset() {
	*x = SerializedIdemixIdentity{}
	mi := &file_msp_identities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedIdemixIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedIdemixIdentity) ProtoMessage() {}

func (x *SerializedIdemixIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_msp_identities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedIdemixIdentity.ProtoReflect.Descriptor instead.
func (*SerializedIdemixIdentity) Descriptor() ([]byte, []int) {
	return file_msp_identities_proto_rawDescGZIP(), []int{1}
}

func (x *SerializedIdemixIdentity) GetNymX() []byte {
	if x != nil {
		return x.NymX
	}
	return nil
}

func (x *SerializedIdemixIdentity) GetNymY() []byte {
	if x != nil {
		return x.NymY
	}
	return nil
}

func (x *SerializedIdemixIdentity) GetOu() []byte {
	if x != nil {
		return x.Ou
	}
	return nil
}

func (x *SerializedIdemixIdentity) GetRole() []byte {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *SerializedIdemixIdentity) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_msp_identities_proto protoreflect.FileDescriptor

const file_msp_identities_proto_rawDesc = "" +
	"\n" +
	"\x14msp/identities.proto\x12\x03msp\"E\n" +
	"\x12SerializedIdentity\x12\x14\n" +
	"\x05mspid\x18\x01 \x01(\tR\x05mspid\x12\x19\n" +
	"\bid_bytes\x18\x02 \x01(\fR\aidBytes\"~\n" +
	"\x18SerializedIdemixIdentity\x12\x13\n" +
	"\x05nym_x\x18\x01 \x01(\fR\x04nymX\x12\x13\n" +
	"\x05nym_y\x18\x02 \x01(\fR\x04nymY\x12\x0e\n" +
	"\x02ou\x18\x03 \x01(\fR\x02ou\x12\x12\n" +
	"\x04role\x18\x04 \x01(\fR\x04role\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proofBP\n" +
	"!org.hyperledger.fabric.protos.mspZ+github.com/hyperledger/fabric-protos-go/mspb\x06proto3"

var (
	file_msp_identities_proto_rawDescOnce sync.Once
	file_msp_identities_proto_rawDescData []byte
)

func file_msp_identities_proto_rawDescGZIP() []byte {
	file_msp_identities_proto_rawDescOnce.Do(func() {
		file_msp_identities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msp_identities_proto_rawDesc), len(file_msp_identities_proto_rawDesc)))
	})
	return file_msp_identities_proto_rawDescData
}

var file_msp_identities_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msp_identities_proto_goTypes = []any{
	(*SerializedIdentity)(nil),       // 0: msp.SerializedIdentity
	(*SerializedIdemixIdentity)(nil), // 1: msp.SerializedIdemixIdentity
}
var file_msp_identities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msp_identities_proto_init() }
func file_msp_identities_proto_init() {
	if File_msp_identities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msp_identities_proto_rawDesc), len(file_msp_identities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msp_identities_proto_goTypes,
		DependencyIndexes: file_msp_identities_proto_depIdxs,
		MessageInfos:      file_msp_identities_proto_msgTypes,
	}.Build()
	File_msp_identities_proto = out.File
	file_msp_identities_proto_goTypes = nil
	file_msp_identities_proto_depIdxs = nil
}
