// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: msp/msp_principal.proto

package msp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSPPrincipal_Classification int32

const (
	MSPPrincipal_ROLE MSPPrincipal_Classification = 0 // Represents the one of the dedicated MSP roles, the
	// one of a member of MSP network, and the one of an
	// administrator of an MSP network
	MSPPrincipal_ORGANIZATION_UNIT MSPPrincipal_Classification = 1 // Denotes a finer grained (affiliation-based)
	// groupping of entities, per MSP affiliation
	// E.g., this can well be represented by an MSP's
	// Organization unit
	MSPPrincipal_IDENTITY MSPPrincipal_Classification = 2 // Denotes a principal that consists of a single
	// identity
	MSPPrincipal_ANONYMITY MSPPrincipal_Classification = 3 // Denotes a principal that can be used to enforce
	// an identity to be anonymous or nominal.
	MSPPrincipal_COMBINED MSPPrincipal_Classification = 4 // Denotes a combined principal
)

// Enum value maps for MSPPrincipal_Classification.
var (
	MSPPrincipal_Classification_name = map[int32]string{
		0: "ROLE",
		1: "ORGANIZATION_UNIT",
		2: "IDENTITY",
		3: "ANONYMITY",
		4: "COMBINED",
	}
	MSPPrincipal_Classification_value = map[string]int32{
		"ROLE":              0,
		"ORGANIZATION_UNIT": 1,
		"IDENTITY":          2,
		"ANONYMITY":         3,
		"COMBINED":          4,
	}
)

func (x MSPPrincipal_Classification) Enum() *MSPPrincipal_Classification {
	p := new(MSPPrincipal_Classification)
	*p = x
	return p
}

func (x MSPPrincipal_Classification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSPPrincipal_Classification) Descriptor() protoreflect.EnumDescriptor {
	return file_msp_msp_principal_proto_enumTypes[0].Descriptor()
}

func (MSPPrincipal_Classification) Type() protoreflect.EnumType {
	return &file_msp_msp_principal_proto_enumTypes[0]
}

func (x MSPPrincipal_Classification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSPPrincipal_Classification.Descriptor instead.
func (MSPPrincipal_Classification) EnumDescriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{0, 0}
}

type MSPRole_MSPRoleType int32

const (
	MSPRole_MEMBER  MSPRole_MSPRoleType = 0 // Represents an MSP Member
	MSPRole_ADMIN   MSPRole_MSPRoleType = 1 // Represents an MSP Admin
	MSPRole_CLIENT  MSPRole_MSPRoleType = 2 // Represents an MSP Client
	MSPRole_PEER    MSPRole_MSPRoleType = 3 // Represents an MSP Peer
	MSPRole_ORDERER MSPRole_MSPRoleType = 4 // Represents an MSP Orderer
)

// Enum value maps for MSPRole_MSPRoleType.
var (
	MSPRole_MSPRoleType_name = map[int32]string{
		0: "MEMBER",
		1: "ADMIN",
		2: "CLIENT",
		3: "PEER",
		4: "ORDERER",
	}
	MSPRole_MSPRoleType_value = map[string]int32{
		"MEMBER":  0,
		"ADMIN":   1,
		"CLIENT":  2,
		"PEER":    3,
		"ORDERER": 4,
	}
)

func (x MSPRole_MSPRoleType) Enum() *MSPRole_MSPRoleType {
	p := new(MSPRole_MSPRoleType)
	*p = x
	return p
}

func (x MSPRole_MSPRoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSPRole_MSPRoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_msp_msp_principal_proto_enumTypes[1].Descriptor()
}

func (MSPRole_MSPRoleType) Type() protoreflect.EnumType {
	return &file_msp_msp_principal_proto_enumTypes[1]
}

func (x MSPRole_MSPRoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSPRole_MSPRoleType.Descriptor instead.
func (MSPRole_MSPRoleType) EnumDescriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{2, 0}
}

type MSPIdentityAnonymity_MSPIdentityAnonymityType int32

const (
	MSPIdentityAnonymity_NOMINAL   MSPIdentityAnonymity_MSPIdentityAnonymityType = 0 // Represents a nominal MSP Identity
	MSPIdentityAnonymity_ANONYMOUS MSPIdentityAnonymity_MSPIdentityAnonymityType = 1 // Represents an anonymous MSP Identity
)

// Enum value maps for MSPIdentityAnonymity_MSPIdentityAnonymityType.
var (
	MSPIdentityAnonymity_MSPIdentityAnonymityType_name = map[int32]string{
		0: "NOMINAL",
		1: "ANONYMOUS",
	}
	MSPIdentityAnonymity_MSPIdentityAnonymityType_value = map[string]int32{
		"NOMINAL":   0,
		"ANONYMOUS": 1,
	}
)

func (x MSPIdentityAnonymity_MSPIdentityAnonymityType) Enum() *MSPIdentityAnonymity_MSPIdentityAnonymityType {
	p := new(MSPIdentityAnonymity_MSPIdentityAnonymityType)
	*p = x
	return p
}

func (x MSPIdentityAnonymity_MSPIdentityAnonymityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSPIdentityAnonymity_MSPIdentityAnonymityType) Descriptor() protoreflect.EnumDescriptor {
	return file_msp_msp_principal_proto_enumTypes[2].Descriptor()
}

func (MSPIdentityAnonymity_MSPIdentityAnonymityType) Type() protoreflect.EnumType {
	return &file_msp_msp_principal_proto_enumTypes[2]
}

func (x MSPIdentityAnonymity_MSPIdentityAnonymityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSPIdentityAnonymity_MSPIdentityAnonymityType.Descriptor instead.
func (MSPIdentityAnonymity_MSPIdentityAnonymityType) EnumDescriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{3, 0}
}

// MSPPrincipal aims to represent an MSP-centric set of identities.
// In particular, this structure allows for definition of
//   - a group of identities that are member of the same MSP
//   - a group of identities that are member of the same organization unit
//     in the same MSP
//   - a group of identities that are administering a specific MSP
//   - a specific identity
//
// Expressing these groups is done given two fields of the fields below
//   - Classification, that defines the type of classification of identities
//     in an MSP this principal would be defined on; Classification can take
//     three values:
//     (i)  ByMSPRole: that represents a classification of identities within
//     MSP based on one of the two pre-defined MSP rules, "member" and "admin"
//     (ii) ByOrganizationUnit: that represents a classification of identities
//     within MSP based on the organization unit an identity belongs to
//     (iii)ByIdentity that denotes that MSPPrincipal is mapped to a single
//     identity/certificate; this would mean that the Principal bytes
//     message
type MSPPrincipal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Classification describes the way that one should process
	// Principal. An Classification value of "ByOrganizationUnit" reflects
	// that "Principal" contains the name of an organization this MSP
	// handles. A Classification value "ByIdentity" means that
	// "Principal" contains a specific identity. Default value
	// denotes that Principal contains one of the groups by
	// default supported by all MSPs ("admin" or "member").
	PrincipalClassification MSPPrincipal_Classification `protobuf:"varint,1,opt,name=principal_classification,json=principalClassification,proto3,enum=common.MSPPrincipal_Classification" json:"principal_classification,omitempty"`
	// Principal completes the policy principal definition. For the default
	// principal types, Principal can be either "Admin" or "Member".
	// For the ByOrganizationUnit/ByIdentity values of Classification,
	// PolicyPrincipal acquires its value from an organization unit or
	// identity, respectively.
	// For the Combined Classification type, the Principal is a marshalled
	// CombinedPrincipal.
	Principal     []byte `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSPPrincipal) Reset() {
	*x = MSPPrincipal{}
	mi := &file_msp_msp_principal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSPPrincipal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSPPrincipal) ProtoMessage() {}

func (x *MSPPrincipal) ProtoReflect() protoreflect.Message {
	mi := &file_msp_msp_principal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSPPrincipal.ProtoReflect.Descriptor instead.
func (*MSPPrincipal) Descriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{0}
}

func (x *MSPPrincipal) GetPrincipalClassification() MSPPrincipal_Classification {
	if x != nil {
		return x.PrincipalClassification
	}
	return MSPPrincipal_ROLE
}

func (x *MSPPrincipal) GetPrincipal() []byte {
	if x != nil {
		return x.Principal
	}
	return nil
}

// OrganizationUnit governs the organization of the Principal
// field of a policy principal when a specific organization unity members
// are to be defined within a policy principal.
type OrganizationUnit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MSPIdentifier represents the identifier of the MSP this organization unit
	// refers to
	MspIdentifier string `protobuf:"bytes,1,opt,name=msp_identifier,json=mspIdentifier,proto3" json:"msp_identifier,omitempty"`
	// OrganizationUnitIdentifier defines the organizational unit under the
	// MSP identified with MSPIdentifier
	OrganizationalUnitIdentifier string `protobuf:"bytes,2,opt,name=organizational_unit_identifier,json=organizationalUnitIdentifier,proto3" json:"organizational_unit_identifier,omitempty"`
	// CertifiersIdentifier is the hash of certificates chain of trust
	// related to this organizational unit
	CertifiersIdentifier []byte `protobuf:"bytes,3,opt,name=certifiers_identifier,json=certifiersIdentifier,proto3" json:"certifiers_identifier,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrganizationUnit) Reset() {
	*x = OrganizationUnit{}
	mi := &file_msp_msp_principal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationUnit) ProtoMessage() {}

func (x *OrganizationUnit) ProtoReflect() protoreflect.Message {
	mi := &file_msp_msp_principal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationUnit.ProtoReflect.Descriptor instead.
func (*OrganizationUnit) Descriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizationUnit) GetMspIdentifier() string {
	if x != nil {
		return x.MspIdentifier
	}
	return ""
}

func (x *OrganizationUnit) GetOrganizationalUnitIdentifier() string {
	if x != nil {
		return x.OrganizationalUnitIdentifier
	}
	return ""
}

func (x *OrganizationUnit) GetCertifiersIdentifier() []byte {
	if x != nil {
		return x.CertifiersIdentifier
	}
	return nil
}

// MSPRole governs the organization of the Principal
// field of an MSPPrincipal when it aims to define one of the
// two dedicated roles within an MSP: Admin and Members.
type MSPRole struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MSPIdentifier represents the identifier of the MSP this principal
	// refers to
	MspIdentifier string `protobuf:"bytes,1,opt,name=msp_identifier,json=mspIdentifier,proto3" json:"msp_identifier,omitempty"`
	// MSPRoleType defines which of the available, pre-defined MSP-roles
	// an identiy should posess inside the MSP with identifier MSPidentifier
	Role          MSPRole_MSPRoleType `protobuf:"varint,2,opt,name=role,proto3,enum=common.MSPRole_MSPRoleType" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSPRole) Reset() {
	*x = MSPRole{}
	mi := &file_msp_msp_principal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSPRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSPRole) ProtoMessage() {}

func (x *MSPRole) ProtoReflect() protoreflect.Message {
	mi := &file_msp_msp_principal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSPRole.ProtoReflect.Descriptor instead.
func (*MSPRole) Descriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{2}
}

func (x *MSPRole) GetMspIdentifier() string {
	if x != nil {
		return x.MspIdentifier
	}
	return ""
}

func (x *MSPRole) GetRole() MSPRole_MSPRoleType {
	if x != nil {
		return x.Role
	}
	return MSPRole_MEMBER
}

// MSPIdentityAnonymity can be used to enforce an identity to be anonymous or nominal.
type MSPIdentityAnonymity struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	AnonymityType MSPIdentityAnonymity_MSPIdentityAnonymityType `protobuf:"varint,1,opt,name=anonymity_type,json=anonymityType,proto3,enum=common.MSPIdentityAnonymity_MSPIdentityAnonymityType" json:"anonymity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSPIdentityAnonymity) Reset() {
	*x = MSPIdentityAnonymity{}
	mi := &file_msp_msp_principal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSPIdentityAnonymity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSPIdentityAnonymity) ProtoMessage() {}

func (x *MSPIdentityAnonymity) ProtoReflect() protoreflect.Message {
	mi := &file_msp_msp_principal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSPIdentityAnonymity.ProtoReflect.Descriptor instead.
func (*MSPIdentityAnonymity) Descriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{3}
}

func (x *MSPIdentityAnonymity) GetAnonymityType() MSPIdentityAnonymity_MSPIdentityAnonymityType {
	if x != nil {
		return x.AnonymityType
	}
	return MSPIdentityAnonymity_NOMINAL
}

// CombinedPrincipal governs the organization of the Principal
// field of a policy principal when principal_classification has
// indicated that a combined form of principals is required
type CombinedPrincipal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Principals refer to combined principals
	Principals    []*MSPPrincipal `protobuf:"bytes,1,rep,name=principals,proto3" json:"principals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedPrincipal) Reset() {
	*x = CombinedPrincipal{}
	mi := &file_msp_msp_principal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedPrincipal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedPrincipal) ProtoMessage() {}

func (x *CombinedPrincipal) ProtoReflect() protoreflect.Message {
	mi := &file_msp_msp_principal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedPrincipal.ProtoReflect.Descriptor instead.
func (*CombinedPrincipal) Descriptor() ([]byte, []int) {
	return file_msp_msp_principal_proto_rawDescGZIP(), []int{4}
}

func (x *CombinedPrincipal) GetPrincipals() []*MSPPrincipal {
	if x != nil {
		return x.Principals
	}
	return nil
}

var File_msp_msp_principal_proto protoreflect.FileDescriptor

const file_msp_msp_principal_proto_rawDesc = "" +
	"\n" +
	"\x17msp/msp_principal.proto\x12\x06common\"\xea\x01\n" +
	"\fMSPPrincipal\x12^\n" +
	"\x18principal_classification\x18\x01 \x01(\x0e2#.common.MSPPrincipal.ClassificationR\x17principalClassification\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\fR\tprincipal\"\\\n" +
	"\x0eClassification\x12\b\n" +
	"\x04ROLE\x10\x00\x12\x15\n" +
	"\x11ORGANIZATION_UNIT\x10\x01\x12\f\n" +
	"\bIDENTITY\x10\x02\x12\r\n" +
	"\tANONYMITY\x10\x03\x12\f\n" +
	"\bCOMBINED\x10\x04\"\xb4\x01\n" +
	"\x10OrganizationUnit\x12%\n" +
	"\x0emsp_identifier\x18\x01 \x01(\tR\rmspIdentifier\x12D\n" +
	"\x1eorganizational_unit_identifier\x18\x02 \x01(\tR\x1corganizationalUnitIdentifier\x123\n" +
	"\x15certifiers_identifier\x18\x03 \x01(\fR\x14certifiersIdentifier\"\xaa\x01\n" +
	"\aMSPRole\x12%\n" +
	"\x0emsp_identifier\x18\x01 \x01(\tR\rmspIdentifier\x12/\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1b.common.MSPRole.MSPRoleTypeR\x04role\"G\n" +
	"\vMSPRoleType\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x02\x12\b\n" +
	"\x04PEER\x10\x03\x12\v\n" +
	"\aORDERER\x10\x04\"\xac\x01\n" +
	"\x14MSPIdentityAnonymity\x12\\\n" +
	"\x0eanonymity_type\x18\x01 \x01(\x0e25.common.MSPIdentityAnonymity.MSPIdentityAnonymityTypeR\ranonymityType\"6\n" +
	"\x18MSPIdentityAnonymityType\x12\v\n" +
	"\aNOMINAL\x10\x00\x12\r\n" +
	"\tANONYMOUS\x10\x01\"I\n" +
	"\x11CombinedPrincipal\x124\n" +
	"\n" +
	"principals\x18\x01 \x03(\v2\x14.common.MSPPrincipalR\n" +
	"principalsBS\n" +
	"$org.hyperledger.fabric.protos.commonZ+github.com/hyperledger/fabric-protos-go/mspb\x06proto3"

var (
	file_msp_msp_principal_proto_rawDescOnce sync.Once
	file_msp_msp_principal_proto_rawDescData []byte
)

func file_msp_msp_principal_proto_rawDescGZIP() []byte {
	file_msp_msp_principal_proto_rawDescOnce.Do(func() {
		file_msp_msp_principal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msp_msp_principal_proto_rawDesc), len(file_msp_msp_principal_proto_rawDesc)))
	})
	return file_msp_msp_principal_proto_rawDescData
}

var file_msp_msp_principal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_msp_msp_principal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_msp_msp_principal_proto_goTypes = []any{
	(MSPPrincipal_Classification)(0),                   // 0: common.MSPPrincipal.Classification
	(MSPRole_MSPRoleType)(0),                           // 1: common.MSPRole.MSPRoleType
	(MSPIdentityAnonymity_MSPIdentityAnonymityType)(0), // 2: common.MSPIdentityAnonymity.MSPIdentityAnonymityType
	(*MSPPrincipal)(nil),                               // 3: common.MSPPrincipal
	(*OrganizationUnit)(nil),                           // 4: common.OrganizationUnit
	(*MSPRole)(nil),                                    // 5: common.MSPRole
	(*MSPIdentityAnonymity)(nil),                       // 6: common.MSPIdentityAnonymity
	(*CombinedPrincipal)(nil),                          // 7: common.CombinedPrincipal
}
var file_msp_msp_principal_proto_depIdxs = []int32{
	0, // 0: common.MSPPrincipal.principal_classification:type_name -> common.MSPPrincipal.Classification
	1, // 1: common.MSPRole.role:type_name -> common.MSPRole.MSPRoleType
	2, // 2: common.MSPIdentityAnonymity.anonymity_type:type_name -> common.MSPIdentityAnonymity.MSPIdentityAnonymityType
	3, // 3: common.CombinedPrincipal.principals:type_name -> common.MSPPrincipal
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msp_msp_principal_proto_init() }
func file_msp_msp_principal_proto_init() {
	if File_msp_msp_principal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msp_msp_principal_proto_rawDesc), len(file_msp_msp_principal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msp_msp_principal_proto_goTypes,
		DependencyIndexes: file_msp_msp_principal_proto_depIdxs,
		EnumInfos:         file_msp_msp_principal_proto_enumTypes,
		MessageInfos:      file_msp_msp_principal_proto_msgTypes,
	}.Build()
	File_msp_msp_principal_proto = out.File
	file_msp_msp_principal_proto_goTypes = nil
	file_msp_msp_principal_proto_depIdxs = nil
}
