// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/chaincode.proto

package peer

import (
	common "github.com/hyperledger/fabric-protos-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChaincodeSpec_Type int32

const (
	ChaincodeSpec_UNDEFINED ChaincodeSpec_Type = 0
	ChaincodeSpec_GOLANG    ChaincodeSpec_Type = 1
	ChaincodeSpec_NODE      ChaincodeSpec_Type = 2
	ChaincodeSpec_CAR       ChaincodeSpec_Type = 3
	ChaincodeSpec_JAVA      ChaincodeSpec_Type = 4
)

// Enum value maps for ChaincodeSpec_Type.
var (
	ChaincodeSpec_Type_name = map[int32]string{
		0: "UNDEFINED",
		1: "GOLANG",
		2: "NODE",
		3: "CAR",
		4: "JAVA",
	}
	ChaincodeSpec_Type_value = map[string]int32{
		"UNDEFINED": 0,
		"GOLANG":    1,
		"NODE":      2,
		"CAR":       3,
		"JAVA":      4,
	}
)

func (x ChaincodeSpec_Type) Enum() *ChaincodeSpec_Type {
	p := new(ChaincodeSpec_Type)
	*p = x
	return p
}

func (x ChaincodeSpec_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChaincodeSpec_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_chaincode_proto_enumTypes[0].Descriptor()
}

func (ChaincodeSpec_Type) Type() protoreflect.EnumType {
	return &file_peer_chaincode_proto_enumTypes[0]
}

func (x ChaincodeSpec_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChaincodeSpec_Type.Descriptor instead.
func (ChaincodeSpec_Type) EnumDescriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{2, 0}
}

// ChaincodeID contains the path as specified by the deploy transaction
// that created it as well as the hashCode that is generated by the
// system for the path. From the user level (ie, CLI, REST API and so on)
// deploy transaction is expected to provide the path and other requests
// are expected to provide the hashCode. The other value will be ignored.
// Internally, the structure could contain both values. For instance, the
// hashCode will be set when first generated using the path
type ChaincodeID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deploy transaction will use the path
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// all other requests will use the name (really a hashcode) generated by
	// the deploy transaction
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// user friendly version name for the chaincode
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeID) Reset() {
	*x = ChaincodeID{}
	mi := &file_peer_chaincode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeID) ProtoMessage() {}

func (x *ChaincodeID) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeID.ProtoReflect.Descriptor instead.
func (*ChaincodeID) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{0}
}

func (x *ChaincodeID) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChaincodeID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChaincodeID) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Carries the chaincode function and its arguments.
// UnmarshalJSON in transaction.go converts the string-based REST/JSON input to
// the []byte-based current ChaincodeInput structure.
type ChaincodeInput struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Args        [][]byte               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Decorations map[string][]byte      `protobuf:"bytes,2,rep,name=decorations,proto3" json:"decorations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// is_init is used for the application to signal that an invocation is to be routed
	// to the legacy 'Init' function for compatibility with chaincodes which handled
	// Init in the old way.  New applications should manage their initialized state
	// themselves.
	IsInit        bool `protobuf:"varint,3,opt,name=is_init,json=isInit,proto3" json:"is_init,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeInput) Reset() {
	*x = ChaincodeInput{}
	mi := &file_peer_chaincode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeInput) ProtoMessage() {}

func (x *ChaincodeInput) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeInput.ProtoReflect.Descriptor instead.
func (*ChaincodeInput) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{1}
}

func (x *ChaincodeInput) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ChaincodeInput) GetDecorations() map[string][]byte {
	if x != nil {
		return x.Decorations
	}
	return nil
}

func (x *ChaincodeInput) GetIsInit() bool {
	if x != nil {
		return x.IsInit
	}
	return false
}

// Carries the chaincode specification. This is the actual metadata required for
// defining a chaincode.
type ChaincodeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChaincodeSpec_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=protos.ChaincodeSpec_Type" json:"type,omitempty"`
	ChaincodeId   *ChaincodeID           `protobuf:"bytes,2,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	Input         *ChaincodeInput        `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeSpec) Reset() {
	*x = ChaincodeSpec{}
	mi := &file_peer_chaincode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeSpec) ProtoMessage() {}

func (x *ChaincodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeSpec.ProtoReflect.Descriptor instead.
func (*ChaincodeSpec) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{2}
}

func (x *ChaincodeSpec) GetType() ChaincodeSpec_Type {
	if x != nil {
		return x.Type
	}
	return ChaincodeSpec_UNDEFINED
}

func (x *ChaincodeSpec) GetChaincodeId() *ChaincodeID {
	if x != nil {
		return x.ChaincodeId
	}
	return nil
}

func (x *ChaincodeSpec) GetInput() *ChaincodeInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ChaincodeSpec) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// Specify the deployment of a chaincode.
// TODO: Define `codePackage`.
type ChaincodeDeploymentSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChaincodeSpec *ChaincodeSpec         `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec,proto3" json:"chaincode_spec,omitempty"`
	CodePackage   []byte                 `protobuf:"bytes,3,opt,name=code_package,json=codePackage,proto3" json:"code_package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeDeploymentSpec) Reset() {
	*x = ChaincodeDeploymentSpec{}
	mi := &file_peer_chaincode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeDeploymentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeDeploymentSpec) ProtoMessage() {}

func (x *ChaincodeDeploymentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeDeploymentSpec.ProtoReflect.Descriptor instead.
func (*ChaincodeDeploymentSpec) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{3}
}

func (x *ChaincodeDeploymentSpec) GetChaincodeSpec() *ChaincodeSpec {
	if x != nil {
		return x.ChaincodeSpec
	}
	return nil
}

func (x *ChaincodeDeploymentSpec) GetCodePackage() []byte {
	if x != nil {
		return x.CodePackage
	}
	return nil
}

// Carries the chaincode function and its arguments.
type ChaincodeInvocationSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChaincodeSpec *ChaincodeSpec         `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec,proto3" json:"chaincode_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeInvocationSpec) Reset() {
	*x = ChaincodeInvocationSpec{}
	mi := &file_peer_chaincode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeInvocationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeInvocationSpec) ProtoMessage() {}

func (x *ChaincodeInvocationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeInvocationSpec.ProtoReflect.Descriptor instead.
func (*ChaincodeInvocationSpec) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{4}
}

func (x *ChaincodeInvocationSpec) GetChaincodeSpec() *ChaincodeSpec {
	if x != nil {
		return x.ChaincodeSpec
	}
	return nil
}

// LifecycleEvent is used as the payload of the chaincode event emitted by LSCC
type LifecycleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChaincodeName string                 `protobuf:"bytes,1,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleEvent) Reset() {
	*x = LifecycleEvent{}
	mi := &file_peer_chaincode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEvent) ProtoMessage() {}

func (x *LifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEvent.ProtoReflect.Descriptor instead.
func (*LifecycleEvent) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{5}
}

func (x *LifecycleEvent) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

// CDSData is data stored in the LSCC on instantiation of a CC
// for CDSPackage.  This needs to be serialized for ChaincodeData
// hence the protobuf format
type CDSData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                 // hash of ChaincodeDeploymentSpec.code_package
	Metadatahash  []byte                 `protobuf:"bytes,2,opt,name=metadatahash,proto3" json:"metadatahash,omitempty"` // hash of ChaincodeID.name + ChaincodeID.version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDSData) Reset() {
	*x = CDSData{}
	mi := &file_peer_chaincode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDSData) ProtoMessage() {}

func (x *CDSData) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDSData.ProtoReflect.Descriptor instead.
func (*CDSData) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{6}
}

func (x *CDSData) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CDSData) GetMetadatahash() []byte {
	if x != nil {
		return x.Metadatahash
	}
	return nil
}

// ChaincodeData defines the datastructure for chaincodes to be serialized by proto
// Type provides an additional check by directing to use a specific package after instantiation
// Data is Type specific (see CDSPackage and SignedCDSPackage)
type ChaincodeData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the chaincode
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the chaincode
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Escc for the chaincode instance
	Escc string `protobuf:"bytes,3,opt,name=escc,proto3" json:"escc,omitempty"`
	// Vscc for the chaincode instance
	Vscc string `protobuf:"bytes,4,opt,name=vscc,proto3" json:"vscc,omitempty"`
	// Policy endorsement policy for the chaincode instance
	Policy *common.SignaturePolicyEnvelope `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	// Data data specific to the package
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// Id of the chaincode that's the unique fingerprint for the CC This is not
	// currently used anywhere but serves as a good eyecatcher
	Id []byte `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	// InstantiationPolicy for the chaincode
	InstantiationPolicy *common.SignaturePolicyEnvelope `protobuf:"bytes,8,opt,name=instantiation_policy,json=instantiationPolicy,proto3" json:"instantiation_policy,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChaincodeData) Reset() {
	*x = ChaincodeData{}
	mi := &file_peer_chaincode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeData) ProtoMessage() {}

func (x *ChaincodeData) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeData.ProtoReflect.Descriptor instead.
func (*ChaincodeData) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{7}
}

func (x *ChaincodeData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChaincodeData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ChaincodeData) GetEscc() string {
	if x != nil {
		return x.Escc
	}
	return ""
}

func (x *ChaincodeData) GetVscc() string {
	if x != nil {
		return x.Vscc
	}
	return ""
}

func (x *ChaincodeData) GetPolicy() *common.SignaturePolicyEnvelope {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ChaincodeData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChaincodeData) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ChaincodeData) GetInstantiationPolicy() *common.SignaturePolicyEnvelope {
	if x != nil {
		return x.InstantiationPolicy
	}
	return nil
}

// ChaincodeAdditionalParams - parameters passed to chaincode to notify about peer capabilities
type ChaincodeAdditionalParams struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UseWriteBatch          bool                   `protobuf:"varint,1,opt,name=use_write_batch,json=useWriteBatch,proto3" json:"use_write_batch,omitempty"`                                // an indication that the peer can handle state write batches
	MaxSizeWriteBatch      uint32                 `protobuf:"varint,2,opt,name=max_size_write_batch,json=maxSizeWriteBatch,proto3" json:"max_size_write_batch,omitempty"`                  // maximum size of batches with write state
	UseGetMultipleKeys     bool                   `protobuf:"varint,3,opt,name=use_get_multiple_keys,json=useGetMultipleKeys,proto3" json:"use_get_multiple_keys,omitempty"`               // an indication that the peer can handle get multiple keys
	MaxSizeGetMultipleKeys uint32                 `protobuf:"varint,4,opt,name=max_size_get_multiple_keys,json=maxSizeGetMultipleKeys,proto3" json:"max_size_get_multiple_keys,omitempty"` // maximum size of batches with get multiple keys
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChaincodeAdditionalParams) Reset() {
	*x = ChaincodeAdditionalParams{}
	mi := &file_peer_chaincode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeAdditionalParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeAdditionalParams) ProtoMessage() {}

func (x *ChaincodeAdditionalParams) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeAdditionalParams.ProtoReflect.Descriptor instead.
func (*ChaincodeAdditionalParams) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_proto_rawDescGZIP(), []int{8}
}

func (x *ChaincodeAdditionalParams) GetUseWriteBatch() bool {
	if x != nil {
		return x.UseWriteBatch
	}
	return false
}

func (x *ChaincodeAdditionalParams) GetMaxSizeWriteBatch() uint32 {
	if x != nil {
		return x.MaxSizeWriteBatch
	}
	return 0
}

func (x *ChaincodeAdditionalParams) GetUseGetMultipleKeys() bool {
	if x != nil {
		return x.UseGetMultipleKeys
	}
	return false
}

func (x *ChaincodeAdditionalParams) GetMaxSizeGetMultipleKeys() uint32 {
	if x != nil {
		return x.MaxSizeGetMultipleKeys
	}
	return 0
}

var File_peer_chaincode_proto protoreflect.FileDescriptor

const file_peer_chaincode_proto_rawDesc = "" +
	"\n" +
	"\x14peer/chaincode.proto\x12\x06protos\x1a\x15common/policies.proto\"O\n" +
	"\vChaincodeID\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xc8\x01\n" +
	"\x0eChaincodeInput\x12\x12\n" +
	"\x04args\x18\x01 \x03(\fR\x04args\x12I\n" +
	"\vdecorations\x18\x02 \x03(\v2'.protos.ChaincodeInput.DecorationsEntryR\vdecorations\x12\x17\n" +
	"\ais_init\x18\x03 \x01(\bR\x06isInit\x1a>\n" +
	"\x10DecorationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xff\x01\n" +
	"\rChaincodeSpec\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.protos.ChaincodeSpec.TypeR\x04type\x126\n" +
	"\fchaincode_id\x18\x02 \x01(\v2\x13.protos.ChaincodeIDR\vchaincodeId\x12,\n" +
	"\x05input\x18\x03 \x01(\v2\x16.protos.ChaincodeInputR\x05input\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\">\n" +
	"\x04Type\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\n" +
	"\n" +
	"\x06GOLANG\x10\x01\x12\b\n" +
	"\x04NODE\x10\x02\x12\a\n" +
	"\x03CAR\x10\x03\x12\b\n" +
	"\x04JAVA\x10\x04\"\xa0\x01\n" +
	"\x17ChaincodeDeploymentSpec\x12<\n" +
	"\x0echaincode_spec\x18\x01 \x01(\v2\x15.protos.ChaincodeSpecR\rchaincodeSpec\x12!\n" +
	"\fcode_package\x18\x03 \x01(\fR\vcodePackageJ\x04\b\x02\x10\x03J\x04\b\x04\x10\x05R\x0eeffective_dateR\bexec_env\"p\n" +
	"\x17ChaincodeInvocationSpec\x12<\n" +
	"\x0echaincode_spec\x18\x01 \x01(\v2\x15.protos.ChaincodeSpecR\rchaincodeSpecJ\x04\b\x02\x10\x03R\x11id_generation_alg\"7\n" +
	"\x0eLifecycleEvent\x12%\n" +
	"\x0echaincode_name\x18\x01 \x01(\tR\rchaincodeName\"A\n" +
	"\aCDSData\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\"\n" +
	"\fmetadatahash\x18\x02 \x01(\fR\fmetadatahash\"\x96\x02\n" +
	"\rChaincodeData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04escc\x18\x03 \x01(\tR\x04escc\x12\x12\n" +
	"\x04vscc\x18\x04 \x01(\tR\x04vscc\x127\n" +
	"\x06policy\x18\x05 \x01(\v2\x1f.common.SignaturePolicyEnvelopeR\x06policy\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x0e\n" +
	"\x02id\x18\a \x01(\fR\x02id\x12R\n" +
	"\x14instantiation_policy\x18\b \x01(\v2\x1f.common.SignaturePolicyEnvelopeR\x13instantiationPolicy\"\xe3\x01\n" +
	"\x19ChaincodeAdditionalParams\x12&\n" +
	"\x0fuse_write_batch\x18\x01 \x01(\bR\ruseWriteBatch\x12/\n" +
	"\x14max_size_write_batch\x18\x02 \x01(\rR\x11maxSizeWriteBatch\x121\n" +
	"\x15use_get_multiple_keys\x18\x03 \x01(\bR\x12useGetMultipleKeys\x12:\n" +
	"\x1amax_size_get_multiple_keys\x18\x04 \x01(\rR\x16maxSizeGetMultipleKeysBR\n" +
	"\"org.hyperledger.fabric.protos.peerZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_chaincode_proto_rawDescOnce sync.Once
	file_peer_chaincode_proto_rawDescData []byte
)

func file_peer_chaincode_proto_rawDescGZIP() []byte {
	file_peer_chaincode_proto_rawDescOnce.Do(func() {
		file_peer_chaincode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_chaincode_proto_rawDesc), len(file_peer_chaincode_proto_rawDesc)))
	})
	return file_peer_chaincode_proto_rawDescData
}

var file_peer_chaincode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peer_chaincode_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_peer_chaincode_proto_goTypes = []any{
	(ChaincodeSpec_Type)(0),                // 0: protos.ChaincodeSpec.Type
	(*ChaincodeID)(nil),                    // 1: protos.ChaincodeID
	(*ChaincodeInput)(nil),                 // 2: protos.ChaincodeInput
	(*ChaincodeSpec)(nil),                  // 3: protos.ChaincodeSpec
	(*ChaincodeDeploymentSpec)(nil),        // 4: protos.ChaincodeDeploymentSpec
	(*ChaincodeInvocationSpec)(nil),        // 5: protos.ChaincodeInvocationSpec
	(*LifecycleEvent)(nil),                 // 6: protos.LifecycleEvent
	(*CDSData)(nil),                        // 7: protos.CDSData
	(*ChaincodeData)(nil),                  // 8: protos.ChaincodeData
	(*ChaincodeAdditionalParams)(nil),      // 9: protos.ChaincodeAdditionalParams
	nil,                                    // 10: protos.ChaincodeInput.DecorationsEntry
	(*common.SignaturePolicyEnvelope)(nil), // 11: common.SignaturePolicyEnvelope
}
var file_peer_chaincode_proto_depIdxs = []int32{
	10, // 0: protos.ChaincodeInput.decorations:type_name -> protos.ChaincodeInput.DecorationsEntry
	0,  // 1: protos.ChaincodeSpec.type:type_name -> protos.ChaincodeSpec.Type
	1,  // 2: protos.ChaincodeSpec.chaincode_id:type_name -> protos.ChaincodeID
	2,  // 3: protos.ChaincodeSpec.input:type_name -> protos.ChaincodeInput
	3,  // 4: protos.ChaincodeDeploymentSpec.chaincode_spec:type_name -> protos.ChaincodeSpec
	3,  // 5: protos.ChaincodeInvocationSpec.chaincode_spec:type_name -> protos.ChaincodeSpec
	11, // 6: protos.ChaincodeData.policy:type_name -> common.SignaturePolicyEnvelope
	11, // 7: protos.ChaincodeData.instantiation_policy:type_name -> common.SignaturePolicyEnvelope
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_peer_chaincode_proto_init() }
func file_peer_chaincode_proto_init() {
	if File_peer_chaincode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_chaincode_proto_rawDesc), len(file_peer_chaincode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_chaincode_proto_goTypes,
		DependencyIndexes: file_peer_chaincode_proto_depIdxs,
		EnumInfos:         file_peer_chaincode_proto_enumTypes,
		MessageInfos:      file_peer_chaincode_proto_msgTypes,
	}.Build()
	File_peer_chaincode_proto = out.File
	file_peer_chaincode_proto_goTypes = nil
	file_peer_chaincode_proto_depIdxs = nil
}
