// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/chaincode_shim.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED             ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER              ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED            ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT                  ChaincodeMessage_Type = 3
	ChaincodeMessage_READY                 ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION           ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED             ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR                 ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE             ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE             ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE             ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE      ChaincodeMessage_Type = 11
	ChaincodeMessage_RESPONSE              ChaincodeMessage_Type = 13
	ChaincodeMessage_GET_STATE_BY_RANGE    ChaincodeMessage_Type = 14
	ChaincodeMessage_GET_QUERY_RESULT      ChaincodeMessage_Type = 15
	ChaincodeMessage_QUERY_STATE_NEXT      ChaincodeMessage_Type = 16
	ChaincodeMessage_QUERY_STATE_CLOSE     ChaincodeMessage_Type = 17
	ChaincodeMessage_KEEPALIVE             ChaincodeMessage_Type = 18
	ChaincodeMessage_GET_HISTORY_FOR_KEY   ChaincodeMessage_Type = 19
	ChaincodeMessage_GET_STATE_METADATA    ChaincodeMessage_Type = 20
	ChaincodeMessage_PUT_STATE_METADATA    ChaincodeMessage_Type = 21
	ChaincodeMessage_GET_PRIVATE_DATA_HASH ChaincodeMessage_Type = 22
	ChaincodeMessage_PURGE_PRIVATE_DATA    ChaincodeMessage_Type = 23
	ChaincodeMessage_WRITE_BATCH_STATE     ChaincodeMessage_Type = 24
	ChaincodeMessage_GET_STATE_MULTIPLE    ChaincodeMessage_Type = 25
)

// Enum value maps for ChaincodeMessage_Type.
var (
	ChaincodeMessage_Type_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "REGISTER",
		2:  "REGISTERED",
		3:  "INIT",
		4:  "READY",
		5:  "TRANSACTION",
		6:  "COMPLETED",
		7:  "ERROR",
		8:  "GET_STATE",
		9:  "PUT_STATE",
		10: "DEL_STATE",
		11: "INVOKE_CHAINCODE",
		13: "RESPONSE",
		14: "GET_STATE_BY_RANGE",
		15: "GET_QUERY_RESULT",
		16: "QUERY_STATE_NEXT",
		17: "QUERY_STATE_CLOSE",
		18: "KEEPALIVE",
		19: "GET_HISTORY_FOR_KEY",
		20: "GET_STATE_METADATA",
		21: "PUT_STATE_METADATA",
		22: "GET_PRIVATE_DATA_HASH",
		23: "PURGE_PRIVATE_DATA",
		24: "WRITE_BATCH_STATE",
		25: "GET_STATE_MULTIPLE",
	}
	ChaincodeMessage_Type_value = map[string]int32{
		"UNDEFINED":             0,
		"REGISTER":              1,
		"REGISTERED":            2,
		"INIT":                  3,
		"READY":                 4,
		"TRANSACTION":           5,
		"COMPLETED":             6,
		"ERROR":                 7,
		"GET_STATE":             8,
		"PUT_STATE":             9,
		"DEL_STATE":             10,
		"INVOKE_CHAINCODE":      11,
		"RESPONSE":              13,
		"GET_STATE_BY_RANGE":    14,
		"GET_QUERY_RESULT":      15,
		"QUERY_STATE_NEXT":      16,
		"QUERY_STATE_CLOSE":     17,
		"KEEPALIVE":             18,
		"GET_HISTORY_FOR_KEY":   19,
		"GET_STATE_METADATA":    20,
		"PUT_STATE_METADATA":    21,
		"GET_PRIVATE_DATA_HASH": 22,
		"PURGE_PRIVATE_DATA":    23,
		"WRITE_BATCH_STATE":     24,
		"GET_STATE_MULTIPLE":    25,
	}
)

func (x ChaincodeMessage_Type) Enum() *ChaincodeMessage_Type {
	p := new(ChaincodeMessage_Type)
	*p = x
	return p
}

func (x ChaincodeMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChaincodeMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_chaincode_shim_proto_enumTypes[0].Descriptor()
}

func (ChaincodeMessage_Type) Type() protoreflect.EnumType {
	return &file_peer_chaincode_shim_proto_enumTypes[0]
}

func (x ChaincodeMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChaincodeMessage_Type.Descriptor instead.
func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{0, 0}
}

type WriteRecord_Type int32

const (
	WriteRecord_UNDEFINED          WriteRecord_Type = 0
	WriteRecord_PUT_STATE          WriteRecord_Type = 9
	WriteRecord_DEL_STATE          WriteRecord_Type = 10
	WriteRecord_PUT_STATE_METADATA WriteRecord_Type = 21
	WriteRecord_PURGE_PRIVATE_DATA WriteRecord_Type = 23
)

// Enum value maps for WriteRecord_Type.
var (
	WriteRecord_Type_name = map[int32]string{
		0:  "UNDEFINED",
		9:  "PUT_STATE",
		10: "DEL_STATE",
		21: "PUT_STATE_METADATA",
		23: "PURGE_PRIVATE_DATA",
	}
	WriteRecord_Type_value = map[string]int32{
		"UNDEFINED":          0,
		"PUT_STATE":          9,
		"DEL_STATE":          10,
		"PUT_STATE_METADATA": 21,
		"PURGE_PRIVATE_DATA": 23,
	}
)

func (x WriteRecord_Type) Enum() *WriteRecord_Type {
	p := new(WriteRecord_Type)
	*p = x
	return p
}

func (x WriteRecord_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteRecord_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_chaincode_shim_proto_enumTypes[1].Descriptor()
}

func (WriteRecord_Type) Type() protoreflect.EnumType {
	return &file_peer_chaincode_shim_proto_enumTypes[1]
}

func (x WriteRecord_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteRecord_Type.Descriptor instead.
func (WriteRecord_Type) EnumDescriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{8, 0}
}

type ChaincodeMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      ChaincodeMessage_Type  `protobuf:"varint,1,opt,name=type,proto3,enum=protos.ChaincodeMessage_Type" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid      string                 `protobuf:"bytes,4,opt,name=txid,proto3" json:"txid,omitempty"`
	Proposal  *SignedProposal        `protobuf:"bytes,5,opt,name=proposal,proto3" json:"proposal,omitempty"`
	// event emitted by chaincode. Used only with Init or Invoke.
	// This event is then stored (currently)
	// with Block.NonHashData.TransactionResult
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,6,opt,name=chaincode_event,json=chaincodeEvent,proto3" json:"chaincode_event,omitempty"`
	// channel id
	ChannelId     string `protobuf:"bytes,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeMessage) Reset() {
	*x = ChaincodeMessage{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeMessage) ProtoMessage() {}

func (x *ChaincodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeMessage.ProtoReflect.Descriptor instead.
func (*ChaincodeMessage) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{0}
}

func (x *ChaincodeMessage) GetType() ChaincodeMessage_Type {
	if x != nil {
		return x.Type
	}
	return ChaincodeMessage_UNDEFINED
}

func (x *ChaincodeMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChaincodeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChaincodeMessage) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *ChaincodeMessage) GetProposal() *SignedProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if x != nil {
		return x.ChaincodeEvent
	}
	return nil
}

func (x *ChaincodeMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// GetState is the payload of a ChaincodeMessage. It contains a key which
// is to be fetched from the ledger. If the collection is specified, the key
// would be fetched from the collection (i.e., private state)
type GetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetState) Reset() {
	*x = GetState{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetState) ProtoMessage() {}

func (x *GetState) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetState.ProtoReflect.Descriptor instead.
func (*GetState) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{1}
}

func (x *GetState) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetState) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type GetStateMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateMetadata) Reset() {
	*x = GetStateMetadata{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateMetadata) ProtoMessage() {}

func (x *GetStateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateMetadata.ProtoReflect.Descriptor instead.
func (*GetStateMetadata) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{2}
}

func (x *GetStateMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetStateMetadata) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

// GetStateMultiple is the payload of the ChaincodeMessage.
// It contains the keys to be retrieved from the ledger.
// If a collection is specified, the keys will be retrieved
// from the collection (i.e., the private state).
type GetStateMultiple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateMultiple) Reset() {
	*x = GetStateMultiple{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateMultiple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateMultiple) ProtoMessage() {}

func (x *GetStateMultiple) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateMultiple.ProtoReflect.Descriptor instead.
func (*GetStateMultiple) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{3}
}

func (x *GetStateMultiple) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetStateMultiple) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

// GetStateMultipleResult is result of executing the GetStateMiltiple request
type GetStateMultipleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateMultipleResult) Reset() {
	*x = GetStateMultipleResult{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateMultipleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateMultipleResult) ProtoMessage() {}

func (x *GetStateMultipleResult) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateMultipleResult.ProtoReflect.Descriptor instead.
func (*GetStateMultipleResult) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{4}
}

func (x *GetStateMultipleResult) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// PutState is the payload of a ChaincodeMessage. It contains a key and value
// which needs to be written to the transaction's write set. If the collection is
// specified, the key and value would be written to the transaction's private
// write set.
type PutState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutState) Reset() {
	*x = PutState{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutState) ProtoMessage() {}

func (x *PutState) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutState.ProtoReflect.Descriptor instead.
func (*PutState) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{5}
}

func (x *PutState) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutState) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutState) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type PutStateMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      *StateMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutStateMetadata) Reset() {
	*x = PutStateMetadata{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStateMetadata) ProtoMessage() {}

func (x *PutStateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStateMetadata.ProtoReflect.Descriptor instead.
func (*PutStateMetadata) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{6}
}

func (x *PutStateMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutStateMetadata) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PutStateMetadata) GetMetadata() *StateMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// WriteBatchState - set of records for state changes sent by the batch
type WriteBatchState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rec           []*WriteRecord         `protobuf:"bytes,1,rep,name=rec,proto3" json:"rec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchState) Reset() {
	*x = WriteBatchState{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchState) ProtoMessage() {}

func (x *WriteBatchState) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchState.ProtoReflect.Descriptor instead.
func (*WriteBatchState) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{7}
}

func (x *WriteBatchState) GetRec() []*WriteRecord {
	if x != nil {
		return x.Rec
	}
	return nil
}

// WriteRecord - single record with changes in the state of different types.
// Filled in depending on the type.
type WriteRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      *StateMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Type          WriteRecord_Type       `protobuf:"varint,5,opt,name=type,proto3,enum=protos.WriteRecord_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRecord) Reset() {
	*x = WriteRecord{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRecord) ProtoMessage() {}

func (x *WriteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRecord.ProtoReflect.Descriptor instead.
func (*WriteRecord) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{8}
}

func (x *WriteRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WriteRecord) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WriteRecord) GetMetadata() *StateMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WriteRecord) GetType() WriteRecord_Type {
	if x != nil {
		return x.Type
	}
	return WriteRecord_UNDEFINED
}

// DelState is the payload of a ChaincodeMessage. It contains a key which
// needs to be recorded in the transaction's write set as a delete operation.
// If the collection is specified, the key needs to be recorded in the
// transaction's private write set as a delete operation.
type DelState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelState) Reset() {
	*x = DelState{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelState) ProtoMessage() {}

func (x *DelState) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelState.ProtoReflect.Descriptor instead.
func (*DelState) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{9}
}

func (x *DelState) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DelState) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type PurgePrivateState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgePrivateState) Reset() {
	*x = PurgePrivateState{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgePrivateState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgePrivateState) ProtoMessage() {}

func (x *PurgePrivateState) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgePrivateState.ProtoReflect.Descriptor instead.
func (*PurgePrivateState) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{10}
}

func (x *PurgePrivateState) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PurgePrivateState) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

// GetStateByRange is the payload of a ChaincodeMessage. It contains a start key and
// a end key required to execute range query. If the collection is specified,
// the range query needs to be executed on the private data. The metadata hold
// the byte representation of QueryMetadata.
type GetStateByRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      string                 `protobuf:"bytes,1,opt,name=startKey,proto3" json:"startKey,omitempty"`
	EndKey        string                 `protobuf:"bytes,2,opt,name=endKey,proto3" json:"endKey,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateByRange) Reset() {
	*x = GetStateByRange{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateByRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateByRange) ProtoMessage() {}

func (x *GetStateByRange) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateByRange.ProtoReflect.Descriptor instead.
func (*GetStateByRange) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{11}
}

func (x *GetStateByRange) GetStartKey() string {
	if x != nil {
		return x.StartKey
	}
	return ""
}

func (x *GetStateByRange) GetEndKey() string {
	if x != nil {
		return x.EndKey
	}
	return ""
}

func (x *GetStateByRange) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetStateByRange) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetQueryResult is the payload of a ChaincodeMessage. It contains a query
// string in the form that is supported by the underlying state database.
// If the collection is specified, the query needs to be executed on the
// private data.  The metadata hold the byte representation of QueryMetadata.
type GetQueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryResult) Reset() {
	*x = GetQueryResult{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryResult) ProtoMessage() {}

func (x *GetQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryResult.ProtoReflect.Descriptor instead.
func (*GetQueryResult) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{12}
}

func (x *GetQueryResult) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetQueryResult) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetQueryResult) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// QueryMetadata is the metadata of a GetStateByRange and GetQueryResult.
// It contains a pageSize which denotes the number of records to be fetched
// and a bookmark.
type QueryMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Bookmark      string                 `protobuf:"bytes,2,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetadata) Reset() {
	*x = QueryMetadata{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetadata) ProtoMessage() {}

func (x *QueryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetadata.ProtoReflect.Descriptor instead.
func (*QueryMetadata) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{13}
}

func (x *QueryMetadata) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryMetadata) GetBookmark() string {
	if x != nil {
		return x.Bookmark
	}
	return ""
}

// GetHistoryForKey is the payload of a ChaincodeMessage. It contains a key
// for which the historical values need to be retrieved.
type GetHistoryForKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryForKey) Reset() {
	*x = GetHistoryForKey{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryForKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryForKey) ProtoMessage() {}

func (x *GetHistoryForKey) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryForKey.ProtoReflect.Descriptor instead.
func (*GetHistoryForKey) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{14}
}

func (x *GetHistoryForKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type QueryStateNext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateNext) Reset() {
	*x = QueryStateNext{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateNext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateNext) ProtoMessage() {}

func (x *QueryStateNext) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateNext.ProtoReflect.Descriptor instead.
func (*QueryStateNext) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{15}
}

func (x *QueryStateNext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryStateClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateClose) Reset() {
	*x = QueryStateClose{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateClose) ProtoMessage() {}

func (x *QueryStateClose) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateClose.ProtoReflect.Descriptor instead.
func (*QueryStateClose) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{16}
}

func (x *QueryStateClose) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// QueryResultBytes hold the byte representation of a record returned by the peer.
type QueryResultBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultBytes   []byte                 `protobuf:"bytes,1,opt,name=resultBytes,proto3" json:"resultBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultBytes) Reset() {
	*x = QueryResultBytes{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultBytes) ProtoMessage() {}

func (x *QueryResultBytes) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultBytes.ProtoReflect.Descriptor instead.
func (*QueryResultBytes) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{17}
}

func (x *QueryResultBytes) GetResultBytes() []byte {
	if x != nil {
		return x.ResultBytes
	}
	return nil
}

// QueryResponse is returned by the peer as a result of a GetStateByRange,
// GetQueryResult, and GetHistoryForKey. It holds a bunch of records in
// results field, a flag to denote whether more results need to be fetched from
// the peer in has_more field, transaction id in id field, and a QueryResponseMetadata
// in metadata field.
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QueryResultBytes    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{18}
}

func (x *QueryResponse) GetResults() []*QueryResultBytes {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *QueryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryResponse) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// QueryResponseMetadata is the metadata of a QueryResponse. It contains a count
// which denotes the number of records fetched from the ledger and a bookmark.
type QueryResponseMetadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FetchedRecordsCount int32                  `protobuf:"varint,1,opt,name=fetched_records_count,json=fetchedRecordsCount,proto3" json:"fetched_records_count,omitempty"`
	Bookmark            string                 `protobuf:"bytes,2,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResponseMetadata) Reset() {
	*x = QueryResponseMetadata{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponseMetadata) ProtoMessage() {}

func (x *QueryResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponseMetadata.ProtoReflect.Descriptor instead.
func (*QueryResponseMetadata) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{19}
}

func (x *QueryResponseMetadata) GetFetchedRecordsCount() int32 {
	if x != nil {
		return x.FetchedRecordsCount
	}
	return 0
}

func (x *QueryResponseMetadata) GetBookmark() string {
	if x != nil {
		return x.Bookmark
	}
	return ""
}

type StateMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metakey       string                 `protobuf:"bytes,1,opt,name=metakey,proto3" json:"metakey,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateMetadata) Reset() {
	*x = StateMetadata{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateMetadata) ProtoMessage() {}

func (x *StateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateMetadata.ProtoReflect.Descriptor instead.
func (*StateMetadata) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{20}
}

func (x *StateMetadata) GetMetakey() string {
	if x != nil {
		return x.Metakey
	}
	return ""
}

func (x *StateMetadata) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StateMetadataResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StateMetadata       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateMetadataResult) Reset() {
	*x = StateMetadataResult{}
	mi := &file_peer_chaincode_shim_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateMetadataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateMetadataResult) ProtoMessage() {}

func (x *StateMetadataResult) ProtoReflect() protoreflect.Message {
	mi := &file_peer_chaincode_shim_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateMetadataResult.ProtoReflect.Descriptor instead.
func (*StateMetadataResult) Descriptor() ([]byte, []int) {
	return file_peer_chaincode_shim_proto_rawDescGZIP(), []int{21}
}

func (x *StateMetadataResult) GetEntries() []*StateMetadata {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_peer_chaincode_shim_proto protoreflect.FileDescriptor

const file_peer_chaincode_shim_proto_rawDesc = "" +
	"\n" +
	"\x19peer/chaincode_shim.proto\x12\x06protos\x1a\x1apeer/chaincode_event.proto\x1a\x13peer/proposal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x06\n" +
	"\x10ChaincodeMessage\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.protos.ChaincodeMessage.TypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x12\n" +
	"\x04txid\x18\x04 \x01(\tR\x04txid\x122\n" +
	"\bproposal\x18\x05 \x01(\v2\x16.protos.SignedProposalR\bproposal\x12?\n" +
	"\x0fchaincode_event\x18\x06 \x01(\v2\x16.protos.ChaincodeEventR\x0echaincodeEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\a \x01(\tR\tchannelId\"\xd9\x03\n" +
	"\x04Type\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\x0e\n" +
	"\n" +
	"REGISTERED\x10\x02\x12\b\n" +
	"\x04INIT\x10\x03\x12\t\n" +
	"\x05READY\x10\x04\x12\x0f\n" +
	"\vTRANSACTION\x10\x05\x12\r\n" +
	"\tCOMPLETED\x10\x06\x12\t\n" +
	"\x05ERROR\x10\a\x12\r\n" +
	"\tGET_STATE\x10\b\x12\r\n" +
	"\tPUT_STATE\x10\t\x12\r\n" +
	"\tDEL_STATE\x10\n" +
	"\x12\x14\n" +
	"\x10INVOKE_CHAINCODE\x10\v\x12\f\n" +
	"\bRESPONSE\x10\r\x12\x16\n" +
	"\x12GET_STATE_BY_RANGE\x10\x0e\x12\x14\n" +
	"\x10GET_QUERY_RESULT\x10\x0f\x12\x14\n" +
	"\x10QUERY_STATE_NEXT\x10\x10\x12\x15\n" +
	"\x11QUERY_STATE_CLOSE\x10\x11\x12\r\n" +
	"\tKEEPALIVE\x10\x12\x12\x17\n" +
	"\x13GET_HISTORY_FOR_KEY\x10\x13\x12\x16\n" +
	"\x12GET_STATE_METADATA\x10\x14\x12\x16\n" +
	"\x12PUT_STATE_METADATA\x10\x15\x12\x19\n" +
	"\x15GET_PRIVATE_DATA_HASH\x10\x16\x12\x16\n" +
	"\x12PURGE_PRIVATE_DATA\x10\x17\x12\x15\n" +
	"\x11WRITE_BATCH_STATE\x10\x18\x12\x16\n" +
	"\x12GET_STATE_MULTIPLE\x10\x19\"<\n" +
	"\bGetState\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"D\n" +
	"\x10GetStateMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"F\n" +
	"\x10GetStateMultiple\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"0\n" +
	"\x16GetStateMultipleResult\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"R\n" +
	"\bPutState\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\"w\n" +
	"\x10PutStateMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x121\n" +
	"\bmetadata\x18\x04 \x01(\v2\x15.protos.StateMetadataR\bmetadata\"8\n" +
	"\x0fWriteBatchState\x12%\n" +
	"\x03rec\x18\x01 \x03(\v2\x13.protos.WriteRecordR\x03rec\"\x9b\x02\n" +
	"\vWriteRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x121\n" +
	"\bmetadata\x18\x04 \x01(\v2\x15.protos.StateMetadataR\bmetadata\x12,\n" +
	"\x04type\x18\x05 \x01(\x0e2\x18.protos.WriteRecord.TypeR\x04type\"c\n" +
	"\x04Type\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\r\n" +
	"\tPUT_STATE\x10\t\x12\r\n" +
	"\tDEL_STATE\x10\n" +
	"\x12\x16\n" +
	"\x12PUT_STATE_METADATA\x10\x15\x12\x16\n" +
	"\x12PURGE_PRIVATE_DATA\x10\x17\"<\n" +
	"\bDelState\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"E\n" +
	"\x11PurgePrivateState\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"\x81\x01\n" +
	"\x0fGetStateByRange\x12\x1a\n" +
	"\bstartKey\x18\x01 \x01(\tR\bstartKey\x12\x16\n" +
	"\x06endKey\x18\x02 \x01(\tR\x06endKey\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\"b\n" +
	"\x0eGetQueryResult\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\"G\n" +
	"\rQueryMetadata\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bbookmark\x18\x02 \x01(\tR\bbookmark\"$\n" +
	"\x10GetHistoryForKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\" \n" +
	"\x0eQueryStateNext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fQueryStateClose\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x10QueryResultBytes\x12 \n" +
	"\vresultBytes\x18\x01 \x01(\fR\vresultBytes\"\x8a\x01\n" +
	"\rQueryResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.protos.QueryResultBytesR\aresults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\"g\n" +
	"\x15QueryResponseMetadata\x122\n" +
	"\x15fetched_records_count\x18\x01 \x01(\x05R\x13fetchedRecordsCount\x12\x1a\n" +
	"\bbookmark\x18\x02 \x01(\tR\bbookmark\"?\n" +
	"\rStateMetadata\x12\x18\n" +
	"\ametakey\x18\x01 \x01(\tR\ametakey\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"F\n" +
	"\x13StateMetadataResult\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.protos.StateMetadataR\aentries2V\n" +
	"\x10ChaincodeSupport\x12B\n" +
	"\bRegister\x12\x18.protos.ChaincodeMessage\x1a\x18.protos.ChaincodeMessage(\x010\x012N\n" +
	"\tChaincode\x12A\n" +
	"\aConnect\x12\x18.protos.ChaincodeMessage\x1a\x18.protos.ChaincodeMessage(\x010\x01BR\n" +
	"\"org.hyperledger.fabric.protos.peerZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_chaincode_shim_proto_rawDescOnce sync.Once
	file_peer_chaincode_shim_proto_rawDescData []byte
)

func file_peer_chaincode_shim_proto_rawDescGZIP() []byte {
	file_peer_chaincode_shim_proto_rawDescOnce.Do(func() {
		file_peer_chaincode_shim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_chaincode_shim_proto_rawDesc), len(file_peer_chaincode_shim_proto_rawDesc)))
	})
	return file_peer_chaincode_shim_proto_rawDescData
}

var file_peer_chaincode_shim_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_peer_chaincode_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_peer_chaincode_shim_proto_goTypes = []any{
	(ChaincodeMessage_Type)(0),     // 0: protos.ChaincodeMessage.Type
	(WriteRecord_Type)(0),          // 1: protos.WriteRecord.Type
	(*ChaincodeMessage)(nil),       // 2: protos.ChaincodeMessage
	(*GetState)(nil),               // 3: protos.GetState
	(*GetStateMetadata)(nil),       // 4: protos.GetStateMetadata
	(*GetStateMultiple)(nil),       // 5: protos.GetStateMultiple
	(*GetStateMultipleResult)(nil), // 6: protos.GetStateMultipleResult
	(*PutState)(nil),               // 7: protos.PutState
	(*PutStateMetadata)(nil),       // 8: protos.PutStateMetadata
	(*WriteBatchState)(nil),        // 9: protos.WriteBatchState
	(*WriteRecord)(nil),            // 10: protos.WriteRecord
	(*DelState)(nil),               // 11: protos.DelState
	(*PurgePrivateState)(nil),      // 12: protos.PurgePrivateState
	(*GetStateByRange)(nil),        // 13: protos.GetStateByRange
	(*GetQueryResult)(nil),         // 14: protos.GetQueryResult
	(*QueryMetadata)(nil),          // 15: protos.QueryMetadata
	(*GetHistoryForKey)(nil),       // 16: protos.GetHistoryForKey
	(*QueryStateNext)(nil),         // 17: protos.QueryStateNext
	(*QueryStateClose)(nil),        // 18: protos.QueryStateClose
	(*QueryResultBytes)(nil),       // 19: protos.QueryResultBytes
	(*QueryResponse)(nil),          // 20: protos.QueryResponse
	(*QueryResponseMetadata)(nil),  // 21: protos.QueryResponseMetadata
	(*StateMetadata)(nil),          // 22: protos.StateMetadata
	(*StateMetadataResult)(nil),    // 23: protos.StateMetadataResult
	(*timestamppb.Timestamp)(nil),  // 24: google.protobuf.Timestamp
	(*SignedProposal)(nil),         // 25: protos.SignedProposal
	(*ChaincodeEvent)(nil),         // 26: protos.ChaincodeEvent
}
var file_peer_chaincode_shim_proto_depIdxs = []int32{
	0,  // 0: protos.ChaincodeMessage.type:type_name -> protos.ChaincodeMessage.Type
	24, // 1: protos.ChaincodeMessage.timestamp:type_name -> google.protobuf.Timestamp
	25, // 2: protos.ChaincodeMessage.proposal:type_name -> protos.SignedProposal
	26, // 3: protos.ChaincodeMessage.chaincode_event:type_name -> protos.ChaincodeEvent
	22, // 4: protos.PutStateMetadata.metadata:type_name -> protos.StateMetadata
	10, // 5: protos.WriteBatchState.rec:type_name -> protos.WriteRecord
	22, // 6: protos.WriteRecord.metadata:type_name -> protos.StateMetadata
	1,  // 7: protos.WriteRecord.type:type_name -> protos.WriteRecord.Type
	19, // 8: protos.QueryResponse.results:type_name -> protos.QueryResultBytes
	22, // 9: protos.StateMetadataResult.entries:type_name -> protos.StateMetadata
	2,  // 10: protos.ChaincodeSupport.Register:input_type -> protos.ChaincodeMessage
	2,  // 11: protos.Chaincode.Connect:input_type -> protos.ChaincodeMessage
	2,  // 12: protos.ChaincodeSupport.Register:output_type -> protos.ChaincodeMessage
	2,  // 13: protos.Chaincode.Connect:output_type -> protos.ChaincodeMessage
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_peer_chaincode_shim_proto_init() }
func file_peer_chaincode_shim_proto_init() {
	if File_peer_chaincode_shim_proto != nil {
		return
	}
	file_peer_chaincode_event_proto_init()
	file_peer_proposal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_chaincode_shim_proto_rawDesc), len(file_peer_chaincode_shim_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_peer_chaincode_shim_proto_goTypes,
		DependencyIndexes: file_peer_chaincode_shim_proto_depIdxs,
		EnumInfos:         file_peer_chaincode_shim_proto_enumTypes,
		MessageInfos:      file_peer_chaincode_shim_proto_msgTypes,
	}.Build()
	File_peer_chaincode_shim_proto = out.File
	file_peer_chaincode_shim_proto_goTypes = nil
	file_peer_chaincode_shim_proto_depIdxs = nil
}
