// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/collection.proto

package peer

import (
	common "github.com/hyperledger/fabric-protos-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CollectionConfigPackage represents an array of CollectionConfig
// messages; the extra struct is required because repeated oneof is
// forbidden by the protobuf syntax
type CollectionConfigPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []*CollectionConfig    `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionConfigPackage) Reset() {
	*x = CollectionConfigPackage{}
	mi := &file_peer_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionConfigPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionConfigPackage) ProtoMessage() {}

func (x *CollectionConfigPackage) ProtoReflect() protoreflect.Message {
	mi := &file_peer_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionConfigPackage.ProtoReflect.Descriptor instead.
func (*CollectionConfigPackage) Descriptor() ([]byte, []int) {
	return file_peer_collection_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionConfigPackage) GetConfig() []*CollectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// CollectionConfig defines the configuration of a collection object;
// it currently contains a single, static type.
// Dynamic collections are deferred.
type CollectionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CollectionConfig_StaticCollectionConfig
	Payload       isCollectionConfig_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionConfig) Reset() {
	*x = CollectionConfig{}
	mi := &file_peer_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionConfig) ProtoMessage() {}

func (x *CollectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peer_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionConfig.ProtoReflect.Descriptor instead.
func (*CollectionConfig) Descriptor() ([]byte, []int) {
	return file_peer_collection_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionConfig) GetPayload() isCollectionConfig_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CollectionConfig) GetStaticCollectionConfig() *StaticCollectionConfig {
	if x != nil {
		if x, ok := x.Payload.(*CollectionConfig_StaticCollectionConfig); ok {
			return x.StaticCollectionConfig
		}
	}
	return nil
}

type isCollectionConfig_Payload interface {
	isCollectionConfig_Payload()
}

type CollectionConfig_StaticCollectionConfig struct {
	StaticCollectionConfig *StaticCollectionConfig `protobuf:"bytes,1,opt,name=static_collection_config,json=staticCollectionConfig,proto3,oneof"`
}

func (*CollectionConfig_StaticCollectionConfig) isCollectionConfig_Payload() {}

// StaticCollectionConfig constitutes the configuration parameters of a
// static collection object. Static collections are collections that are
// known at chaincode instantiation time, and that cannot be changed.
// Dynamic collections are deferred.
type StaticCollectionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the collection inside the denoted chaincode
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// a reference to a policy residing / managed in the config block
	// to define which orgs have access to this collection’s private data
	MemberOrgsPolicy *CollectionPolicyConfig `protobuf:"bytes,2,opt,name=member_orgs_policy,json=memberOrgsPolicy,proto3" json:"member_orgs_policy,omitempty"`
	// The minimum number of peers private data will be sent to upon
	// endorsement. The endorsement would fail if dissemination to at least
	// this number of peers is not achieved.
	RequiredPeerCount int32 `protobuf:"varint,3,opt,name=required_peer_count,json=requiredPeerCount,proto3" json:"required_peer_count,omitempty"`
	// The maximum number of peers that private data will be sent to
	// upon endorsement. This number has to be bigger than required_peer_count.
	MaximumPeerCount int32 `protobuf:"varint,4,opt,name=maximum_peer_count,json=maximumPeerCount,proto3" json:"maximum_peer_count,omitempty"`
	// The number of blocks after which the collection data expires.
	// For instance if the value is set to 10, a key last modified by block number 100
	// will be purged at block number 111. A zero value is treated same as MaxUint64
	BlockToLive uint64 `protobuf:"varint,5,opt,name=block_to_live,json=blockToLive,proto3" json:"block_to_live,omitempty"`
	// The member only read access denotes whether only collection member clients
	// can read the private data (if set to true), or even non members can
	// read the data (if set to false, for example if you want to implement more granular
	// access logic in the chaincode)
	MemberOnlyRead bool `protobuf:"varint,6,opt,name=member_only_read,json=memberOnlyRead,proto3" json:"member_only_read,omitempty"`
	// The member only write access denotes whether only collection member clients
	// can write the private data (if set to true), or even non members can
	// write the data (if set to false, for example if you want to implement more granular
	// access logic in the chaincode)
	MemberOnlyWrite bool `protobuf:"varint,7,opt,name=member_only_write,json=memberOnlyWrite,proto3" json:"member_only_write,omitempty"`
	// a reference to a policy residing / managed in the config block
	// to define the endorsement policy for this collection
	EndorsementPolicy *ApplicationPolicy `protobuf:"bytes,8,opt,name=endorsement_policy,json=endorsementPolicy,proto3" json:"endorsement_policy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StaticCollectionConfig) Reset() {
	*x = StaticCollectionConfig{}
	mi := &file_peer_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticCollectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticCollectionConfig) ProtoMessage() {}

func (x *StaticCollectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peer_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticCollectionConfig.ProtoReflect.Descriptor instead.
func (*StaticCollectionConfig) Descriptor() ([]byte, []int) {
	return file_peer_collection_proto_rawDescGZIP(), []int{2}
}

func (x *StaticCollectionConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaticCollectionConfig) GetMemberOrgsPolicy() *CollectionPolicyConfig {
	if x != nil {
		return x.MemberOrgsPolicy
	}
	return nil
}

func (x *StaticCollectionConfig) GetRequiredPeerCount() int32 {
	if x != nil {
		return x.RequiredPeerCount
	}
	return 0
}

func (x *StaticCollectionConfig) GetMaximumPeerCount() int32 {
	if x != nil {
		return x.MaximumPeerCount
	}
	return 0
}

func (x *StaticCollectionConfig) GetBlockToLive() uint64 {
	if x != nil {
		return x.BlockToLive
	}
	return 0
}

func (x *StaticCollectionConfig) GetMemberOnlyRead() bool {
	if x != nil {
		return x.MemberOnlyRead
	}
	return false
}

func (x *StaticCollectionConfig) GetMemberOnlyWrite() bool {
	if x != nil {
		return x.MemberOnlyWrite
	}
	return false
}

func (x *StaticCollectionConfig) GetEndorsementPolicy() *ApplicationPolicy {
	if x != nil {
		return x.EndorsementPolicy
	}
	return nil
}

// Collection policy configuration. Initially, the configuration can only
// contain a SignaturePolicy. In the future, the SignaturePolicy may be a
// more general Policy. Instead of containing the actual policy, the
// configuration may in the future contain a string reference to a policy.
type CollectionPolicyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CollectionPolicyConfig_SignaturePolicy
	Payload       isCollectionPolicyConfig_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionPolicyConfig) Reset() {
	*x = CollectionPolicyConfig{}
	mi := &file_peer_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionPolicyConfig) ProtoMessage() {}

func (x *CollectionPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peer_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionPolicyConfig.ProtoReflect.Descriptor instead.
func (*CollectionPolicyConfig) Descriptor() ([]byte, []int) {
	return file_peer_collection_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionPolicyConfig) GetPayload() isCollectionPolicyConfig_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CollectionPolicyConfig) GetSignaturePolicy() *common.SignaturePolicyEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*CollectionPolicyConfig_SignaturePolicy); ok {
			return x.SignaturePolicy
		}
	}
	return nil
}

type isCollectionPolicyConfig_Payload interface {
	isCollectionPolicyConfig_Payload()
}

type CollectionPolicyConfig_SignaturePolicy struct {
	// Initially, only a signature policy is supported.
	SignaturePolicy *common.SignaturePolicyEnvelope `protobuf:"bytes,1,opt,name=signature_policy,json=signaturePolicy,proto3,oneof"`
}

func (*CollectionPolicyConfig_SignaturePolicy) isCollectionPolicyConfig_Payload() {}

var File_peer_collection_proto protoreflect.FileDescriptor

const file_peer_collection_proto_rawDesc = "" +
	"\n" +
	"\x15peer/collection.proto\x12\x06protos\x1a\x15common/policies.proto\x1a\x11peer/policy.proto\"K\n" +
	"\x17CollectionConfigPackage\x120\n" +
	"\x06config\x18\x01 \x03(\v2\x18.protos.CollectionConfigR\x06config\"y\n" +
	"\x10CollectionConfig\x12Z\n" +
	"\x18static_collection_config\x18\x01 \x01(\v2\x1e.protos.StaticCollectionConfigH\x00R\x16staticCollectionConfigB\t\n" +
	"\apayload\"\x9c\x03\n" +
	"\x16StaticCollectionConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12L\n" +
	"\x12member_orgs_policy\x18\x02 \x01(\v2\x1e.protos.CollectionPolicyConfigR\x10memberOrgsPolicy\x12.\n" +
	"\x13required_peer_count\x18\x03 \x01(\x05R\x11requiredPeerCount\x12,\n" +
	"\x12maximum_peer_count\x18\x04 \x01(\x05R\x10maximumPeerCount\x12\"\n" +
	"\rblock_to_live\x18\x05 \x01(\x04R\vblockToLive\x12(\n" +
	"\x10member_only_read\x18\x06 \x01(\bR\x0ememberOnlyRead\x12*\n" +
	"\x11member_only_write\x18\a \x01(\bR\x0fmemberOnlyWrite\x12H\n" +
	"\x12endorsement_policy\x18\b \x01(\v2\x19.protos.ApplicationPolicyR\x11endorsementPolicy\"q\n" +
	"\x16CollectionPolicyConfig\x12L\n" +
	"\x10signature_policy\x18\x01 \x01(\v2\x1f.common.SignaturePolicyEnvelopeH\x00R\x0fsignaturePolicyB\t\n" +
	"\apayloadBR\n" +
	"\"org.hyperledger.fabric.protos.peerZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_collection_proto_rawDescOnce sync.Once
	file_peer_collection_proto_rawDescData []byte
)

func file_peer_collection_proto_rawDescGZIP() []byte {
	file_peer_collection_proto_rawDescOnce.Do(func() {
		file_peer_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_collection_proto_rawDesc), len(file_peer_collection_proto_rawDesc)))
	})
	return file_peer_collection_proto_rawDescData
}

var file_peer_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_peer_collection_proto_goTypes = []any{
	(*CollectionConfigPackage)(nil),        // 0: protos.CollectionConfigPackage
	(*CollectionConfig)(nil),               // 1: protos.CollectionConfig
	(*StaticCollectionConfig)(nil),         // 2: protos.StaticCollectionConfig
	(*CollectionPolicyConfig)(nil),         // 3: protos.CollectionPolicyConfig
	(*ApplicationPolicy)(nil),              // 4: protos.ApplicationPolicy
	(*common.SignaturePolicyEnvelope)(nil), // 5: common.SignaturePolicyEnvelope
}
var file_peer_collection_proto_depIdxs = []int32{
	1, // 0: protos.CollectionConfigPackage.config:type_name -> protos.CollectionConfig
	2, // 1: protos.CollectionConfig.static_collection_config:type_name -> protos.StaticCollectionConfig
	3, // 2: protos.StaticCollectionConfig.member_orgs_policy:type_name -> protos.CollectionPolicyConfig
	4, // 3: protos.StaticCollectionConfig.endorsement_policy:type_name -> protos.ApplicationPolicy
	5, // 4: protos.CollectionPolicyConfig.signature_policy:type_name -> common.SignaturePolicyEnvelope
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_peer_collection_proto_init() }
func file_peer_collection_proto_init() {
	if File_peer_collection_proto != nil {
		return
	}
	file_peer_policy_proto_init()
	file_peer_collection_proto_msgTypes[1].OneofWrappers = []any{
		(*CollectionConfig_StaticCollectionConfig)(nil),
	}
	file_peer_collection_proto_msgTypes[3].OneofWrappers = []any{
		(*CollectionPolicyConfig_SignaturePolicy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_collection_proto_rawDesc), len(file_peer_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_collection_proto_goTypes,
		DependencyIndexes: file_peer_collection_proto_depIdxs,
		MessageInfos:      file_peer_collection_proto_msgTypes,
	}.Build()
	File_peer_collection_proto = out.File
	file_peer_collection_proto_goTypes = nil
	file_peer_collection_proto_depIdxs = nil
}
