// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/events.proto

package peer

import (
	common "github.com/hyperledger/fabric-protos-go/common"
	rwset "github.com/hyperledger/fabric-protos-go/ledger/rwset"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FilteredBlock is a minimal set of information about a block
type FilteredBlock struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ChannelId            string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Number               uint64                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"` // The position in the blockchain
	FilteredTransactions []*FilteredTransaction `protobuf:"bytes,4,rep,name=filtered_transactions,json=filteredTransactions,proto3" json:"filtered_transactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FilteredBlock) Reset() {
	*x = FilteredBlock{}
	mi := &file_peer_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredBlock) ProtoMessage() {}

func (x *FilteredBlock) ProtoReflect() protoreflect.Message {
	mi := &file_peer_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredBlock.ProtoReflect.Descriptor instead.
func (*FilteredBlock) Descriptor() ([]byte, []int) {
	return file_peer_events_proto_rawDescGZIP(), []int{0}
}

func (x *FilteredBlock) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *FilteredBlock) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *FilteredBlock) GetFilteredTransactions() []*FilteredTransaction {
	if x != nil {
		return x.FilteredTransactions
	}
	return nil
}

// FilteredTransaction is a minimal set of information about a transaction
// within a block
type FilteredTransaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Txid             string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Type             common.HeaderType      `protobuf:"varint,2,opt,name=type,proto3,enum=common.HeaderType" json:"type,omitempty"`
	TxValidationCode TxValidationCode       `protobuf:"varint,3,opt,name=tx_validation_code,json=txValidationCode,proto3,enum=protos.TxValidationCode" json:"tx_validation_code,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*FilteredTransaction_TransactionActions
	Data          isFilteredTransaction_Data `protobuf_oneof:"Data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilteredTransaction) Reset() {
	*x = FilteredTransaction{}
	mi := &file_peer_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredTransaction) ProtoMessage() {}

func (x *FilteredTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_peer_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredTransaction.ProtoReflect.Descriptor instead.
func (*FilteredTransaction) Descriptor() ([]byte, []int) {
	return file_peer_events_proto_rawDescGZIP(), []int{1}
}

func (x *FilteredTransaction) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *FilteredTransaction) GetType() common.HeaderType {
	if x != nil {
		return x.Type
	}
	return common.HeaderType(0)
}

func (x *FilteredTransaction) GetTxValidationCode() TxValidationCode {
	if x != nil {
		return x.TxValidationCode
	}
	return TxValidationCode_VALID
}

func (x *FilteredTransaction) GetData() isFilteredTransaction_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FilteredTransaction) GetTransactionActions() *FilteredTransactionActions {
	if x != nil {
		if x, ok := x.Data.(*FilteredTransaction_TransactionActions); ok {
			return x.TransactionActions
		}
	}
	return nil
}

type isFilteredTransaction_Data interface {
	isFilteredTransaction_Data()
}

type FilteredTransaction_TransactionActions struct {
	TransactionActions *FilteredTransactionActions `protobuf:"bytes,4,opt,name=transaction_actions,json=transactionActions,proto3,oneof"`
}

func (*FilteredTransaction_TransactionActions) isFilteredTransaction_Data() {}

// FilteredTransactionActions is a wrapper for array of TransactionAction
// message from regular block
type FilteredTransactionActions struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	ChaincodeActions []*FilteredChaincodeAction `protobuf:"bytes,1,rep,name=chaincode_actions,json=chaincodeActions,proto3" json:"chaincode_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FilteredTransactionActions) Reset() {
	*x = FilteredTransactionActions{}
	mi := &file_peer_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredTransactionActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredTransactionActions) ProtoMessage() {}

func (x *FilteredTransactionActions) ProtoReflect() protoreflect.Message {
	mi := &file_peer_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredTransactionActions.ProtoReflect.Descriptor instead.
func (*FilteredTransactionActions) Descriptor() ([]byte, []int) {
	return file_peer_events_proto_rawDescGZIP(), []int{2}
}

func (x *FilteredTransactionActions) GetChaincodeActions() []*FilteredChaincodeAction {
	if x != nil {
		return x.ChaincodeActions
	}
	return nil
}

// FilteredChaincodeAction is a minimal set of information about an action
// within a transaction
type FilteredChaincodeAction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChaincodeEvent *ChaincodeEvent        `protobuf:"bytes,1,opt,name=chaincode_event,json=chaincodeEvent,proto3" json:"chaincode_event,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilteredChaincodeAction) Reset() {
	*x = FilteredChaincodeAction{}
	mi := &file_peer_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilteredChaincodeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredChaincodeAction) ProtoMessage() {}

func (x *FilteredChaincodeAction) ProtoReflect() protoreflect.Message {
	mi := &file_peer_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredChaincodeAction.ProtoReflect.Descriptor instead.
func (*FilteredChaincodeAction) Descriptor() ([]byte, []int) {
	return file_peer_events_proto_rawDescGZIP(), []int{3}
}

func (x *FilteredChaincodeAction) GetChaincodeEvent() *ChaincodeEvent {
	if x != nil {
		return x.ChaincodeEvent
	}
	return nil
}

// BlockAndPrivateData contains Block and a map from tx_seq_in_block to rwset.TxPvtReadWriteSet
type BlockAndPrivateData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Block *common.Block          `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	// map from tx_seq_in_block to rwset.TxPvtReadWriteSet
	PrivateDataMap map[uint64]*rwset.TxPvtReadWriteSet `protobuf:"bytes,2,rep,name=private_data_map,json=privateDataMap,proto3" json:"private_data_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockAndPrivateData) Reset() {
	*x = BlockAndPrivateData{}
	mi := &file_peer_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAndPrivateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAndPrivateData) ProtoMessage() {}

func (x *BlockAndPrivateData) ProtoReflect() protoreflect.Message {
	mi := &file_peer_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAndPrivateData.ProtoReflect.Descriptor instead.
func (*BlockAndPrivateData) Descriptor() ([]byte, []int) {
	return file_peer_events_proto_rawDescGZIP(), []int{4}
}

func (x *BlockAndPrivateData) GetBlock() *common.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockAndPrivateData) GetPrivateDataMap() map[uint64]*rwset.TxPvtReadWriteSet {
	if x != nil {
		return x.PrivateDataMap
	}
	return nil
}

// DeliverResponse
type DeliverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*DeliverResponse_Status
	//	*DeliverResponse_Block
	//	*DeliverResponse_FilteredBlock
	//	*DeliverResponse_BlockAndPrivateData
	Type          isDeliverResponse_Type `protobuf_oneof:"Type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_peer_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_peer_events_proto_rawDescGZIP(), []int{5}
}

func (x *DeliverResponse) GetType() isDeliverResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *DeliverResponse) GetStatus() common.Status {
	if x != nil {
		if x, ok := x.Type.(*DeliverResponse_Status); ok {
			return x.Status
		}
	}
	return common.Status(0)
}

func (x *DeliverResponse) GetBlock() *common.Block {
	if x != nil {
		if x, ok := x.Type.(*DeliverResponse_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *DeliverResponse) GetFilteredBlock() *FilteredBlock {
	if x != nil {
		if x, ok := x.Type.(*DeliverResponse_FilteredBlock); ok {
			return x.FilteredBlock
		}
	}
	return nil
}

func (x *DeliverResponse) GetBlockAndPrivateData() *BlockAndPrivateData {
	if x != nil {
		if x, ok := x.Type.(*DeliverResponse_BlockAndPrivateData); ok {
			return x.BlockAndPrivateData
		}
	}
	return nil
}

type isDeliverResponse_Type interface {
	isDeliverResponse_Type()
}

type DeliverResponse_Status struct {
	Status common.Status `protobuf:"varint,1,opt,name=status,proto3,enum=common.Status,oneof"`
}

type DeliverResponse_Block struct {
	Block *common.Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type DeliverResponse_FilteredBlock struct {
	FilteredBlock *FilteredBlock `protobuf:"bytes,3,opt,name=filtered_block,json=filteredBlock,proto3,oneof"`
}

type DeliverResponse_BlockAndPrivateData struct {
	BlockAndPrivateData *BlockAndPrivateData `protobuf:"bytes,4,opt,name=block_and_private_data,json=blockAndPrivateData,proto3,oneof"`
}

func (*DeliverResponse_Status) isDeliverResponse_Type() {}

func (*DeliverResponse_Block) isDeliverResponse_Type() {}

func (*DeliverResponse_FilteredBlock) isDeliverResponse_Type() {}

func (*DeliverResponse_BlockAndPrivateData) isDeliverResponse_Type() {}

var File_peer_events_proto protoreflect.FileDescriptor

const file_peer_events_proto_rawDesc = "" +
	"\n" +
	"\x11peer/events.proto\x12\x06protos\x1a\x13common/common.proto\x1a\x18ledger/rwset/rwset.proto\x1a\x1apeer/chaincode_event.proto\x1a\x16peer/transaction.proto\"\x98\x01\n" +
	"\rFilteredBlock\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\x12P\n" +
	"\x15filtered_transactions\x18\x04 \x03(\v2\x1b.protos.FilteredTransactionR\x14filteredTransactions\"\xf8\x01\n" +
	"\x13FilteredTransaction\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.common.HeaderTypeR\x04type\x12F\n" +
	"\x12tx_validation_code\x18\x03 \x01(\x0e2\x18.protos.TxValidationCodeR\x10txValidationCode\x12U\n" +
	"\x13transaction_actions\x18\x04 \x01(\v2\".protos.FilteredTransactionActionsH\x00R\x12transactionActionsB\x06\n" +
	"\x04Data\"j\n" +
	"\x1aFilteredTransactionActions\x12L\n" +
	"\x11chaincode_actions\x18\x01 \x03(\v2\x1f.protos.FilteredChaincodeActionR\x10chaincodeActions\"Z\n" +
	"\x17FilteredChaincodeAction\x12?\n" +
	"\x0fchaincode_event\x18\x01 \x01(\v2\x16.protos.ChaincodeEventR\x0echaincodeEvent\"\xf2\x01\n" +
	"\x13BlockAndPrivateData\x12#\n" +
	"\x05block\x18\x01 \x01(\v2\r.common.BlockR\x05block\x12Y\n" +
	"\x10private_data_map\x18\x02 \x03(\v2/.protos.BlockAndPrivateData.PrivateDataMapEntryR\x0eprivateDataMap\x1a[\n" +
	"\x13PrivateDataMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.rwset.TxPvtReadWriteSetR\x05value:\x028\x01\"\xfe\x01\n" +
	"\x0fDeliverResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.common.StatusH\x00R\x06status\x12%\n" +
	"\x05block\x18\x02 \x01(\v2\r.common.BlockH\x00R\x05block\x12>\n" +
	"\x0efiltered_block\x18\x03 \x01(\v2\x15.protos.FilteredBlockH\x00R\rfilteredBlock\x12R\n" +
	"\x16block_and_private_data\x18\x04 \x01(\v2\x1b.protos.BlockAndPrivateDataH\x00R\x13blockAndPrivateDataB\x06\n" +
	"\x04Type2\xd4\x01\n" +
	"\aDeliver\x12:\n" +
	"\aDeliver\x12\x10.common.Envelope\x1a\x17.protos.DeliverResponse\"\x00(\x010\x01\x12B\n" +
	"\x0fDeliverFiltered\x12\x10.common.Envelope\x1a\x17.protos.DeliverResponse\"\x00(\x010\x01\x12I\n" +
	"\x16DeliverWithPrivateData\x12\x10.common.Envelope\x1a\x17.protos.DeliverResponse\"\x00(\x010\x01Ba\n" +
	"\"org.hyperledger.fabric.protos.peerB\rEventsPackageZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_events_proto_rawDescOnce sync.Once
	file_peer_events_proto_rawDescData []byte
)

func file_peer_events_proto_rawDescGZIP() []byte {
	file_peer_events_proto_rawDescOnce.Do(func() {
		file_peer_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_events_proto_rawDesc), len(file_peer_events_proto_rawDesc)))
	})
	return file_peer_events_proto_rawDescData
}

var file_peer_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_peer_events_proto_goTypes = []any{
	(*FilteredBlock)(nil),              // 0: protos.FilteredBlock
	(*FilteredTransaction)(nil),        // 1: protos.FilteredTransaction
	(*FilteredTransactionActions)(nil), // 2: protos.FilteredTransactionActions
	(*FilteredChaincodeAction)(nil),    // 3: protos.FilteredChaincodeAction
	(*BlockAndPrivateData)(nil),        // 4: protos.BlockAndPrivateData
	(*DeliverResponse)(nil),            // 5: protos.DeliverResponse
	nil,                                // 6: protos.BlockAndPrivateData.PrivateDataMapEntry
	(common.HeaderType)(0),             // 7: common.HeaderType
	(TxValidationCode)(0),              // 8: protos.TxValidationCode
	(*ChaincodeEvent)(nil),             // 9: protos.ChaincodeEvent
	(*common.Block)(nil),               // 10: common.Block
	(common.Status)(0),                 // 11: common.Status
	(*rwset.TxPvtReadWriteSet)(nil),    // 12: rwset.TxPvtReadWriteSet
	(*common.Envelope)(nil),            // 13: common.Envelope
}
var file_peer_events_proto_depIdxs = []int32{
	1,  // 0: protos.FilteredBlock.filtered_transactions:type_name -> protos.FilteredTransaction
	7,  // 1: protos.FilteredTransaction.type:type_name -> common.HeaderType
	8,  // 2: protos.FilteredTransaction.tx_validation_code:type_name -> protos.TxValidationCode
	2,  // 3: protos.FilteredTransaction.transaction_actions:type_name -> protos.FilteredTransactionActions
	3,  // 4: protos.FilteredTransactionActions.chaincode_actions:type_name -> protos.FilteredChaincodeAction
	9,  // 5: protos.FilteredChaincodeAction.chaincode_event:type_name -> protos.ChaincodeEvent
	10, // 6: protos.BlockAndPrivateData.block:type_name -> common.Block
	6,  // 7: protos.BlockAndPrivateData.private_data_map:type_name -> protos.BlockAndPrivateData.PrivateDataMapEntry
	11, // 8: protos.DeliverResponse.status:type_name -> common.Status
	10, // 9: protos.DeliverResponse.block:type_name -> common.Block
	0,  // 10: protos.DeliverResponse.filtered_block:type_name -> protos.FilteredBlock
	4,  // 11: protos.DeliverResponse.block_and_private_data:type_name -> protos.BlockAndPrivateData
	12, // 12: protos.BlockAndPrivateData.PrivateDataMapEntry.value:type_name -> rwset.TxPvtReadWriteSet
	13, // 13: protos.Deliver.Deliver:input_type -> common.Envelope
	13, // 14: protos.Deliver.DeliverFiltered:input_type -> common.Envelope
	13, // 15: protos.Deliver.DeliverWithPrivateData:input_type -> common.Envelope
	5,  // 16: protos.Deliver.Deliver:output_type -> protos.DeliverResponse
	5,  // 17: protos.Deliver.DeliverFiltered:output_type -> protos.DeliverResponse
	5,  // 18: protos.Deliver.DeliverWithPrivateData:output_type -> protos.DeliverResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_peer_events_proto_init() }
func file_peer_events_proto_init() {
	if File_peer_events_proto != nil {
		return
	}
	file_peer_chaincode_event_proto_init()
	file_peer_transaction_proto_init()
	file_peer_events_proto_msgTypes[1].OneofWrappers = []any{
		(*FilteredTransaction_TransactionActions)(nil),
	}
	file_peer_events_proto_msgTypes[5].OneofWrappers = []any{
		(*DeliverResponse_Status)(nil),
		(*DeliverResponse_Block)(nil),
		(*DeliverResponse_FilteredBlock)(nil),
		(*DeliverResponse_BlockAndPrivateData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_events_proto_rawDesc), len(file_peer_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peer_events_proto_goTypes,
		DependencyIndexes: file_peer_events_proto_depIdxs,
		MessageInfos:      file_peer_events_proto_msgTypes,
	}.Build()
	File_peer_events_proto = out.File
	file_peer_events_proto_goTypes = nil
	file_peer_events_proto_depIdxs = nil
}
