// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/proposal.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This structure is necessary to sign the proposal which contains the header
// and the payload. Without this structure, we would have to concatenate the
// header and the payload to verify the signature, which could be expensive
// with large payload
//
// When an endorser receives a SignedProposal message, it should verify the
// signature over the proposal bytes. This verification requires the following
// steps:
//  1. Verification of the validity of the certificate that was used to produce
//     the signature.  The certificate will be available once proposalBytes has
//     been unmarshalled to a Proposal message, and Proposal.header has been
//     unmarshalled to a Header message. While this unmarshalling-before-verifying
//     might not be ideal, it is unavoidable because i) the signature needs to also
//     protect the signing certificate; ii) it is desirable that Header is created
//     once by the client and never changed (for the sake of accountability and
//     non-repudiation). Note also that it is actually impossible to conclusively
//     verify the validity of the certificate included in a Proposal, because the
//     proposal needs to first be endorsed and ordered with respect to certificate
//     expiration transactions. Still, it is useful to pre-filter expired
//     certificates at this stage.
//  2. Verification that the certificate is trusted (signed by a trusted CA) and
//     that it is allowed to transact with us (with respect to some ACLs);
//  3. Verification that the signature on proposalBytes is valid;
//  4. Detect replay attacks;
type SignedProposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bytes of Proposal
	ProposalBytes []byte `protobuf:"bytes,1,opt,name=proposal_bytes,json=proposalBytes,proto3" json:"proposal_bytes,omitempty"`
	// Signaure over proposalBytes; this signature is to be verified against
	// the creator identity contained in the header of the Proposal message
	// marshaled as proposalBytes
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedProposal) Reset() {
	*x = SignedProposal{}
	mi := &file_peer_proposal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedProposal) ProtoMessage() {}

func (x *SignedProposal) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proposal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedProposal.ProtoReflect.Descriptor instead.
func (*SignedProposal) Descriptor() ([]byte, []int) {
	return file_peer_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *SignedProposal) GetProposalBytes() []byte {
	if x != nil {
		return x.ProposalBytes
	}
	return nil
}

func (x *SignedProposal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// A Proposal is sent to an endorser for endorsement.  The proposal contains:
//  1. A header which should be unmarshaled to a Header message.  Note that
//     Header is both the header of a Proposal and of a Transaction, in that i)
//     both headers should be unmarshaled to this message; and ii) it is used to
//     compute cryptographic hashes and signatures.  The header has fields common
//     to all proposals/transactions.  In addition it has a type field for
//     additional customization. An example of this is the ChaincodeHeaderExtension
//     message used to extend the Header for type CHAINCODE.
//  2. A payload whose type depends on the header's type field.
//  3. An extension whose type depends on the header's type field.
//
// Let us see an example. For type CHAINCODE (see the Header message),
// we have the following:
//  1. The header is a Header message whose extensions field is a
//     ChaincodeHeaderExtension message.
//  2. The payload is a ChaincodeProposalPayload message.
//  3. The extension is a ChaincodeAction that might be used to ask the
//     endorsers to endorse a specific ChaincodeAction, thus emulating the
//     submitting peer model.
type Proposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The header of the proposal. It is the bytes of the Header
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The payload of the proposal as defined by the type in the proposal
	// header.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional extensions to the proposal. Its content depends on the Header's
	// type field.  For the type CHAINCODE, it might be the bytes of a
	// ChaincodeAction message.
	Extension     []byte `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_peer_proposal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proposal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_peer_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *Proposal) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Proposal) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Proposal) GetExtension() []byte {
	if x != nil {
		return x.Extension
	}
	return nil
}

// ChaincodeHeaderExtension is the Header's extentions message to be used when
// the Header's type is CHAINCODE.  This extensions is used to specify which
// chaincode to invoke and what should appear on the ledger.
type ChaincodeHeaderExtension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the chaincode to target.
	ChaincodeId   *ChaincodeID `protobuf:"bytes,2,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeHeaderExtension) Reset() {
	*x = ChaincodeHeaderExtension{}
	mi := &file_peer_proposal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeHeaderExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeHeaderExtension) ProtoMessage() {}

func (x *ChaincodeHeaderExtension) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proposal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeHeaderExtension.ProtoReflect.Descriptor instead.
func (*ChaincodeHeaderExtension) Descriptor() ([]byte, []int) {
	return file_peer_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *ChaincodeHeaderExtension) GetChaincodeId() *ChaincodeID {
	if x != nil {
		return x.ChaincodeId
	}
	return nil
}

// ChaincodeProposalPayload is the Proposal's payload message to be used when
// the Header's type is CHAINCODE.  It contains the arguments for this
// invocation.
type ChaincodeProposalPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Input contains the arguments for this invocation. If this invocation
	// deploys a new chaincode, ESCC/VSCC are part of this field.
	// This is usually a marshaled ChaincodeInvocationSpec
	Input []byte `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// TransientMap contains data (e.g. cryptographic material) that might be used
	// to implement some form of application-level confidentiality. The contents
	// of this field are supposed to always be omitted from the transaction and
	// excluded from the ledger.
	TransientMap  map[string][]byte `protobuf:"bytes,2,rep,name=TransientMap,proto3" json:"TransientMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeProposalPayload) Reset() {
	*x = ChaincodeProposalPayload{}
	mi := &file_peer_proposal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeProposalPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeProposalPayload) ProtoMessage() {}

func (x *ChaincodeProposalPayload) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proposal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeProposalPayload.ProtoReflect.Descriptor instead.
func (*ChaincodeProposalPayload) Descriptor() ([]byte, []int) {
	return file_peer_proposal_proto_rawDescGZIP(), []int{3}
}

func (x *ChaincodeProposalPayload) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ChaincodeProposalPayload) GetTransientMap() map[string][]byte {
	if x != nil {
		return x.TransientMap
	}
	return nil
}

// ChaincodeAction contains the executed chaincode results, response, and event.
type ChaincodeAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field contains the read set and the write set produced by the
	// chaincode executing this invocation.
	Results []byte `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	// This field contains the event generated by the chaincode.
	// Only a single marshaled ChaincodeEvent is included.
	Events []byte `protobuf:"bytes,2,opt,name=events,proto3" json:"events,omitempty"`
	// This field contains the result of executing this invocation.
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	// This field contains the ChaincodeID of executing this invocation. Endorser
	// will set it with the ChaincodeID called by endorser while simulating proposal.
	// Committer will validate the version matching with latest chaincode version.
	// Adding ChaincodeID to keep version opens up the possibility of multiple
	// ChaincodeAction per transaction.
	ChaincodeId   *ChaincodeID `protobuf:"bytes,4,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeAction) Reset() {
	*x = ChaincodeAction{}
	mi := &file_peer_proposal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeAction) ProtoMessage() {}

func (x *ChaincodeAction) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proposal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeAction.ProtoReflect.Descriptor instead.
func (*ChaincodeAction) Descriptor() ([]byte, []int) {
	return file_peer_proposal_proto_rawDescGZIP(), []int{4}
}

func (x *ChaincodeAction) GetResults() []byte {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ChaincodeAction) GetEvents() []byte {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ChaincodeAction) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ChaincodeAction) GetChaincodeId() *ChaincodeID {
	if x != nil {
		return x.ChaincodeId
	}
	return nil
}

var File_peer_proposal_proto protoreflect.FileDescriptor

const file_peer_proposal_proto_rawDesc = "" +
	"\n" +
	"\x13peer/proposal.proto\x12\x06protos\x1a\x14peer/chaincode.proto\x1a\x1cpeer/proposal_response.proto\"U\n" +
	"\x0eSignedProposal\x12%\n" +
	"\x0eproposal_bytes\x18\x01 \x01(\fR\rproposalBytes\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"Z\n" +
	"\bProposal\x12\x16\n" +
	"\x06header\x18\x01 \x01(\fR\x06header\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\textension\x18\x03 \x01(\fR\textension\"k\n" +
	"\x18ChaincodeHeaderExtension\x126\n" +
	"\fchaincode_id\x18\x02 \x01(\v2\x13.protos.ChaincodeIDR\vchaincodeIdJ\x04\b\x01\x10\x02R\x11payload_visbility\"\xc9\x01\n" +
	"\x18ChaincodeProposalPayload\x12\x14\n" +
	"\x05input\x18\x01 \x01(\fR\x05input\x12V\n" +
	"\fTransientMap\x18\x02 \x03(\v22.protos.ChaincodeProposalPayload.TransientMapEntryR\fTransientMap\x1a?\n" +
	"\x11TransientMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0fChaincodeAction\x12\x18\n" +
	"\aresults\x18\x01 \x01(\fR\aresults\x12\x16\n" +
	"\x06events\x18\x02 \x01(\fR\x06events\x12,\n" +
	"\bresponse\x18\x03 \x01(\v2\x10.protos.ResponseR\bresponse\x126\n" +
	"\fchaincode_id\x18\x04 \x01(\v2\x13.protos.ChaincodeIDR\vchaincodeIdJ\x04\b\x05\x10\x06R\x10token_operationsBc\n" +
	"\"org.hyperledger.fabric.protos.peerB\x0fProposalPackageZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_proposal_proto_rawDescOnce sync.Once
	file_peer_proposal_proto_rawDescData []byte
)

func file_peer_proposal_proto_rawDescGZIP() []byte {
	file_peer_proposal_proto_rawDescOnce.Do(func() {
		file_peer_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_proposal_proto_rawDesc), len(file_peer_proposal_proto_rawDesc)))
	})
	return file_peer_proposal_proto_rawDescData
}

var file_peer_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_peer_proposal_proto_goTypes = []any{
	(*SignedProposal)(nil),           // 0: protos.SignedProposal
	(*Proposal)(nil),                 // 1: protos.Proposal
	(*ChaincodeHeaderExtension)(nil), // 2: protos.ChaincodeHeaderExtension
	(*ChaincodeProposalPayload)(nil), // 3: protos.ChaincodeProposalPayload
	(*ChaincodeAction)(nil),          // 4: protos.ChaincodeAction
	nil,                              // 5: protos.ChaincodeProposalPayload.TransientMapEntry
	(*ChaincodeID)(nil),              // 6: protos.ChaincodeID
	(*Response)(nil),                 // 7: protos.Response
}
var file_peer_proposal_proto_depIdxs = []int32{
	6, // 0: protos.ChaincodeHeaderExtension.chaincode_id:type_name -> protos.ChaincodeID
	5, // 1: protos.ChaincodeProposalPayload.TransientMap:type_name -> protos.ChaincodeProposalPayload.TransientMapEntry
	7, // 2: protos.ChaincodeAction.response:type_name -> protos.Response
	6, // 3: protos.ChaincodeAction.chaincode_id:type_name -> protos.ChaincodeID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_peer_proposal_proto_init() }
func file_peer_proposal_proto_init() {
	if File_peer_proposal_proto != nil {
		return
	}
	file_peer_chaincode_proto_init()
	file_peer_proposal_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_proposal_proto_rawDesc), len(file_peer_proposal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_proposal_proto_goTypes,
		DependencyIndexes: file_peer_proposal_proto_depIdxs,
		MessageInfos:      file_peer_proposal_proto_msgTypes,
	}.Build()
	File_peer_proposal_proto = out.File
	file_peer_proposal_proto_goTypes = nil
	file_peer_proposal_proto_depIdxs = nil
}
