// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/query.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChaincodeQueryResponse returns information about each chaincode that pertains
// to a query in lscc.go, such as GetChaincodes (returns all chaincodes
// instantiated on a channel), and GetInstalledChaincodes (returns all chaincodes
// installed on a peer)
type ChaincodeQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chaincodes    []*ChaincodeInfo       `protobuf:"bytes,1,rep,name=chaincodes,proto3" json:"chaincodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeQueryResponse) Reset() {
	*x = ChaincodeQueryResponse{}
	mi := &file_peer_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeQueryResponse) ProtoMessage() {}

func (x *ChaincodeQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeQueryResponse.ProtoReflect.Descriptor instead.
func (*ChaincodeQueryResponse) Descriptor() ([]byte, []int) {
	return file_peer_query_proto_rawDescGZIP(), []int{0}
}

func (x *ChaincodeQueryResponse) GetChaincodes() []*ChaincodeInfo {
	if x != nil {
		return x.Chaincodes
	}
	return nil
}

// ChaincodeInfo contains general information about an installed/instantiated
// chaincode
type ChaincodeInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// the path as specified by the install/instantiate transaction
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// the chaincode function upon instantiation and its arguments. This will be
	// blank if the query is returning information about installed chaincodes.
	Input string `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	// the name of the ESCC for this chaincode. This will be
	// blank if the query is returning information about installed chaincodes.
	Escc string `protobuf:"bytes,5,opt,name=escc,proto3" json:"escc,omitempty"`
	// the name of the VSCC for this chaincode. This will be
	// blank if the query is returning information about installed chaincodes.
	Vscc string `protobuf:"bytes,6,opt,name=vscc,proto3" json:"vscc,omitempty"`
	// the chaincode unique id.
	// computed as: H(
	//
	//	  H(name || version) ||
	//	  H(CodePackage)
	//	)
	Id            []byte `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeInfo) Reset() {
	*x = ChaincodeInfo{}
	mi := &file_peer_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeInfo) ProtoMessage() {}

func (x *ChaincodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_peer_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeInfo.ProtoReflect.Descriptor instead.
func (*ChaincodeInfo) Descriptor() ([]byte, []int) {
	return file_peer_query_proto_rawDescGZIP(), []int{1}
}

func (x *ChaincodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChaincodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ChaincodeInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChaincodeInfo) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ChaincodeInfo) GetEscc() string {
	if x != nil {
		return x.Escc
	}
	return ""
}

func (x *ChaincodeInfo) GetVscc() string {
	if x != nil {
		return x.Vscc
	}
	return ""
}

func (x *ChaincodeInfo) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// ChannelQueryResponse returns information about each channel that pertains
// to a query in lscc.go, such as GetChannels (returns all channels for a
// given peer)
type ChannelQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelInfo         `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelQueryResponse) Reset() {
	*x = ChannelQueryResponse{}
	mi := &file_peer_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelQueryResponse) ProtoMessage() {}

func (x *ChannelQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelQueryResponse.ProtoReflect.Descriptor instead.
func (*ChannelQueryResponse) Descriptor() ([]byte, []int) {
	return file_peer_query_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelQueryResponse) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

// ChannelInfo contains general information about channels
type ChannelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_peer_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_peer_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_peer_query_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// JoinBySnapshotStatus contains information about whether or a JoinBySnapshot operation
// is in progress and the related bootstrap dir if it is running.
type JoinBySnapshotStatus struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	InProgress               bool                   `protobuf:"varint,1,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	BootstrappingSnapshotDir string                 `protobuf:"bytes,2,opt,name=bootstrapping_snapshot_dir,json=bootstrappingSnapshotDir,proto3" json:"bootstrapping_snapshot_dir,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JoinBySnapshotStatus) Reset() {
	*x = JoinBySnapshotStatus{}
	mi := &file_peer_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBySnapshotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBySnapshotStatus) ProtoMessage() {}

func (x *JoinBySnapshotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_peer_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBySnapshotStatus.ProtoReflect.Descriptor instead.
func (*JoinBySnapshotStatus) Descriptor() ([]byte, []int) {
	return file_peer_query_proto_rawDescGZIP(), []int{4}
}

func (x *JoinBySnapshotStatus) GetInProgress() bool {
	if x != nil {
		return x.InProgress
	}
	return false
}

func (x *JoinBySnapshotStatus) GetBootstrappingSnapshotDir() string {
	if x != nil {
		return x.BootstrappingSnapshotDir
	}
	return ""
}

var File_peer_query_proto protoreflect.FileDescriptor

const file_peer_query_proto_rawDesc = "" +
	"\n" +
	"\x10peer/query.proto\x12\x06protos\"O\n" +
	"\x16ChaincodeQueryResponse\x125\n" +
	"\n" +
	"chaincodes\x18\x01 \x03(\v2\x15.protos.ChaincodeInfoR\n" +
	"chaincodes\"\x9f\x01\n" +
	"\rChaincodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x12\n" +
	"\x04escc\x18\x05 \x01(\tR\x04escc\x12\x12\n" +
	"\x04vscc\x18\x06 \x01(\tR\x04vscc\x12\x0e\n" +
	"\x02id\x18\a \x01(\fR\x02id\"G\n" +
	"\x14ChannelQueryResponse\x12/\n" +
	"\bchannels\x18\x01 \x03(\v2\x13.protos.ChannelInfoR\bchannels\",\n" +
	"\vChannelInfo\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"u\n" +
	"\x14JoinBySnapshotStatus\x12\x1f\n" +
	"\vin_progress\x18\x01 \x01(\bR\n" +
	"inProgress\x12<\n" +
	"\x1abootstrapping_snapshot_dir\x18\x02 \x01(\tR\x18bootstrappingSnapshotDirBR\n" +
	"\"org.hyperledger.fabric.protos.peerZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_query_proto_rawDescOnce sync.Once
	file_peer_query_proto_rawDescData []byte
)

func file_peer_query_proto_rawDescGZIP() []byte {
	file_peer_query_proto_rawDescOnce.Do(func() {
		file_peer_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_query_proto_rawDesc), len(file_peer_query_proto_rawDesc)))
	})
	return file_peer_query_proto_rawDescData
}

var file_peer_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_peer_query_proto_goTypes = []any{
	(*ChaincodeQueryResponse)(nil), // 0: protos.ChaincodeQueryResponse
	(*ChaincodeInfo)(nil),          // 1: protos.ChaincodeInfo
	(*ChannelQueryResponse)(nil),   // 2: protos.ChannelQueryResponse
	(*ChannelInfo)(nil),            // 3: protos.ChannelInfo
	(*JoinBySnapshotStatus)(nil),   // 4: protos.JoinBySnapshotStatus
}
var file_peer_query_proto_depIdxs = []int32{
	1, // 0: protos.ChaincodeQueryResponse.chaincodes:type_name -> protos.ChaincodeInfo
	3, // 1: protos.ChannelQueryResponse.channels:type_name -> protos.ChannelInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_peer_query_proto_init() }
func file_peer_query_proto_init() {
	if File_peer_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_query_proto_rawDesc), len(file_peer_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_query_proto_goTypes,
		DependencyIndexes: file_peer_query_proto_depIdxs,
		MessageInfos:      file_peer_query_proto_msgTypes,
	}.Build()
	File_peer_query_proto = out.File
	file_peer_query_proto_goTypes = nil
	file_peer_query_proto_depIdxs = nil
}
