// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/resources.proto

package peer

import (
	common "github.com/hyperledger/fabric-protos-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChaincodeIdentifier identifies a piece of chaincode.  For a peer to accept invocations of
// this chaincode, the hash of the installed code must match, as must the version string
// included with the install command.
type ChaincodeIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`       // The hash of the chaincode bytes
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // A user friendly human readable name corresponding to the ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeIdentifier) Reset() {
	*x = ChaincodeIdentifier{}
	mi := &file_peer_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeIdentifier) ProtoMessage() {}

func (x *ChaincodeIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_peer_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeIdentifier.ProtoReflect.Descriptor instead.
func (*ChaincodeIdentifier) Descriptor() ([]byte, []int) {
	return file_peer_resources_proto_rawDescGZIP(), []int{0}
}

func (x *ChaincodeIdentifier) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ChaincodeIdentifier) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ChaincodeValidation instructs the peer how transactions for this chaincode should be
// validated.  The only validation mechanism which ships with fabric today is the standard
// 'vscc' validation mechanism.  This built in validation method utilizes an endorsement policy
// which checks that a sufficient number of signatures have been included.  The 'arguement'
// field encodes any parameters required by the validation implementation.
type ChaincodeValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Specifies which code to run to validate transactions, defaults to 'vscc'
	Argument      []byte                 `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"` // When 'vscc' a marshaled VSCCArgs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeValidation) Reset() {
	*x = ChaincodeValidation{}
	mi := &file_peer_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeValidation) ProtoMessage() {}

func (x *ChaincodeValidation) ProtoReflect() protoreflect.Message {
	mi := &file_peer_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeValidation.ProtoReflect.Descriptor instead.
func (*ChaincodeValidation) Descriptor() ([]byte, []int) {
	return file_peer_resources_proto_rawDescGZIP(), []int{1}
}

func (x *ChaincodeValidation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChaincodeValidation) GetArgument() []byte {
	if x != nil {
		return x.Argument
	}
	return nil
}

// VSCCArgs is passed (marshaled) as a parameter to the VSCC imlementation via the
// argument field of the ChaincodeValidation message.
type VSCCArgs struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EndorsementPolicyRef string                 `protobuf:"bytes,1,opt,name=endorsement_policy_ref,json=endorsementPolicyRef,proto3" json:"endorsement_policy_ref,omitempty"` // A named reference to an endorsement policy,
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VSCCArgs) Reset() {
	*x = VSCCArgs{}
	mi := &file_peer_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VSCCArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSCCArgs) ProtoMessage() {}

func (x *VSCCArgs) ProtoReflect() protoreflect.Message {
	mi := &file_peer_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSCCArgs.ProtoReflect.Descriptor instead.
func (*VSCCArgs) Descriptor() ([]byte, []int) {
	return file_peer_resources_proto_rawDescGZIP(), []int{2}
}

func (x *VSCCArgs) GetEndorsementPolicyRef() string {
	if x != nil {
		return x.EndorsementPolicyRef
	}
	return ""
}

// ChaincodeEndorsement instructs the peer how transactions should be endorsed.  The only
// endorsement mechanism which ships with the fabric today is the standard 'escc' mechanism.
// This code simply simulates the proposal to generate a RW set, then signs the result
// using the peer's local signing identity.
type ChaincodeEndorsement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Specifies what code to run for endorsements, defaults 'escc'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeEndorsement) Reset() {
	*x = ChaincodeEndorsement{}
	mi := &file_peer_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeEndorsement) ProtoMessage() {}

func (x *ChaincodeEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_peer_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeEndorsement.ProtoReflect.Descriptor instead.
func (*ChaincodeEndorsement) Descriptor() ([]byte, []int) {
	return file_peer_resources_proto_rawDescGZIP(), []int{3}
}

func (x *ChaincodeEndorsement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ConfigTree encapsulates channel and resources configuration of a channel.
// Both configurations are represented as common.Config
type ConfigTree struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelConfig   *common.Config         `protobuf:"bytes,1,opt,name=channel_config,json=channelConfig,proto3" json:"channel_config,omitempty"`
	ResourcesConfig *common.Config         `protobuf:"bytes,2,opt,name=resources_config,json=resourcesConfig,proto3" json:"resources_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigTree) Reset() {
	*x = ConfigTree{}
	mi := &file_peer_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigTree) ProtoMessage() {}

func (x *ConfigTree) ProtoReflect() protoreflect.Message {
	mi := &file_peer_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigTree.ProtoReflect.Descriptor instead.
func (*ConfigTree) Descriptor() ([]byte, []int) {
	return file_peer_resources_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigTree) GetChannelConfig() *common.Config {
	if x != nil {
		return x.ChannelConfig
	}
	return nil
}

func (x *ConfigTree) GetResourcesConfig() *common.Config {
	if x != nil {
		return x.ResourcesConfig
	}
	return nil
}

var File_peer_resources_proto protoreflect.FileDescriptor

const file_peer_resources_proto_rawDesc = "" +
	"\n" +
	"\x14peer/resources.proto\x12\x06protos\x1a\x15common/configtx.proto\"C\n" +
	"\x13ChaincodeIdentifier\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"E\n" +
	"\x13ChaincodeValidation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bargument\x18\x02 \x01(\fR\bargument\"@\n" +
	"\bVSCCArgs\x124\n" +
	"\x16endorsement_policy_ref\x18\x01 \x01(\tR\x14endorsementPolicyRef\"*\n" +
	"\x14ChaincodeEndorsement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"~\n" +
	"\n" +
	"ConfigTree\x125\n" +
	"\x0echannel_config\x18\x01 \x01(\v2\x0e.common.ConfigR\rchannelConfig\x129\n" +
	"\x10resources_config\x18\x02 \x01(\v2\x0e.common.ConfigR\x0fresourcesConfigBR\n" +
	"\"org.hyperledger.fabric.protos.peerZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_resources_proto_rawDescOnce sync.Once
	file_peer_resources_proto_rawDescData []byte
)

func file_peer_resources_proto_rawDescGZIP() []byte {
	file_peer_resources_proto_rawDescOnce.Do(func() {
		file_peer_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_resources_proto_rawDesc), len(file_peer_resources_proto_rawDesc)))
	})
	return file_peer_resources_proto_rawDescData
}

var file_peer_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_peer_resources_proto_goTypes = []any{
	(*ChaincodeIdentifier)(nil),  // 0: protos.ChaincodeIdentifier
	(*ChaincodeValidation)(nil),  // 1: protos.ChaincodeValidation
	(*VSCCArgs)(nil),             // 2: protos.VSCCArgs
	(*ChaincodeEndorsement)(nil), // 3: protos.ChaincodeEndorsement
	(*ConfigTree)(nil),           // 4: protos.ConfigTree
	(*common.Config)(nil),        // 5: common.Config
}
var file_peer_resources_proto_depIdxs = []int32{
	5, // 0: protos.ConfigTree.channel_config:type_name -> common.Config
	5, // 1: protos.ConfigTree.resources_config:type_name -> common.Config
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_peer_resources_proto_init() }
func file_peer_resources_proto_init() {
	if File_peer_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_resources_proto_rawDesc), len(file_peer_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_resources_proto_goTypes,
		DependencyIndexes: file_peer_resources_proto_depIdxs,
		MessageInfos:      file_peer_resources_proto_msgTypes,
	}.Build()
	File_peer_resources_proto = out.File
	file_peer_resources_proto_goTypes = nil
	file_peer_resources_proto_depIdxs = nil
}
