// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: peer/transaction.proto

package peer

import (
	common "github.com/hyperledger/fabric-protos-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxValidationCode int32

const (
	TxValidationCode_VALID                        TxValidationCode = 0
	TxValidationCode_NIL_ENVELOPE                 TxValidationCode = 1
	TxValidationCode_BAD_PAYLOAD                  TxValidationCode = 2
	TxValidationCode_BAD_COMMON_HEADER            TxValidationCode = 3
	TxValidationCode_BAD_CREATOR_SIGNATURE        TxValidationCode = 4
	TxValidationCode_INVALID_ENDORSER_TRANSACTION TxValidationCode = 5
	TxValidationCode_INVALID_CONFIG_TRANSACTION   TxValidationCode = 6
	TxValidationCode_UNSUPPORTED_TX_PAYLOAD       TxValidationCode = 7
	TxValidationCode_BAD_PROPOSAL_TXID            TxValidationCode = 8
	TxValidationCode_DUPLICATE_TXID               TxValidationCode = 9
	TxValidationCode_ENDORSEMENT_POLICY_FAILURE   TxValidationCode = 10
	TxValidationCode_MVCC_READ_CONFLICT           TxValidationCode = 11
	TxValidationCode_PHANTOM_READ_CONFLICT        TxValidationCode = 12
	TxValidationCode_UNKNOWN_TX_TYPE              TxValidationCode = 13
	TxValidationCode_TARGET_CHAIN_NOT_FOUND       TxValidationCode = 14
	TxValidationCode_MARSHAL_TX_ERROR             TxValidationCode = 15
	TxValidationCode_NIL_TXACTION                 TxValidationCode = 16
	TxValidationCode_EXPIRED_CHAINCODE            TxValidationCode = 17
	TxValidationCode_CHAINCODE_VERSION_CONFLICT   TxValidationCode = 18
	TxValidationCode_BAD_HEADER_EXTENSION         TxValidationCode = 19
	TxValidationCode_BAD_CHANNEL_HEADER           TxValidationCode = 20
	TxValidationCode_BAD_RESPONSE_PAYLOAD         TxValidationCode = 21
	TxValidationCode_BAD_RWSET                    TxValidationCode = 22
	TxValidationCode_ILLEGAL_WRITESET             TxValidationCode = 23
	TxValidationCode_INVALID_WRITESET             TxValidationCode = 24
	TxValidationCode_INVALID_CHAINCODE            TxValidationCode = 25
	TxValidationCode_NOT_VALIDATED                TxValidationCode = 254
	TxValidationCode_INVALID_OTHER_REASON         TxValidationCode = 255
)

// Enum value maps for TxValidationCode.
var (
	TxValidationCode_name = map[int32]string{
		0:   "VALID",
		1:   "NIL_ENVELOPE",
		2:   "BAD_PAYLOAD",
		3:   "BAD_COMMON_HEADER",
		4:   "BAD_CREATOR_SIGNATURE",
		5:   "INVALID_ENDORSER_TRANSACTION",
		6:   "INVALID_CONFIG_TRANSACTION",
		7:   "UNSUPPORTED_TX_PAYLOAD",
		8:   "BAD_PROPOSAL_TXID",
		9:   "DUPLICATE_TXID",
		10:  "ENDORSEMENT_POLICY_FAILURE",
		11:  "MVCC_READ_CONFLICT",
		12:  "PHANTOM_READ_CONFLICT",
		13:  "UNKNOWN_TX_TYPE",
		14:  "TARGET_CHAIN_NOT_FOUND",
		15:  "MARSHAL_TX_ERROR",
		16:  "NIL_TXACTION",
		17:  "EXPIRED_CHAINCODE",
		18:  "CHAINCODE_VERSION_CONFLICT",
		19:  "BAD_HEADER_EXTENSION",
		20:  "BAD_CHANNEL_HEADER",
		21:  "BAD_RESPONSE_PAYLOAD",
		22:  "BAD_RWSET",
		23:  "ILLEGAL_WRITESET",
		24:  "INVALID_WRITESET",
		25:  "INVALID_CHAINCODE",
		254: "NOT_VALIDATED",
		255: "INVALID_OTHER_REASON",
	}
	TxValidationCode_value = map[string]int32{
		"VALID":                        0,
		"NIL_ENVELOPE":                 1,
		"BAD_PAYLOAD":                  2,
		"BAD_COMMON_HEADER":            3,
		"BAD_CREATOR_SIGNATURE":        4,
		"INVALID_ENDORSER_TRANSACTION": 5,
		"INVALID_CONFIG_TRANSACTION":   6,
		"UNSUPPORTED_TX_PAYLOAD":       7,
		"BAD_PROPOSAL_TXID":            8,
		"DUPLICATE_TXID":               9,
		"ENDORSEMENT_POLICY_FAILURE":   10,
		"MVCC_READ_CONFLICT":           11,
		"PHANTOM_READ_CONFLICT":        12,
		"UNKNOWN_TX_TYPE":              13,
		"TARGET_CHAIN_NOT_FOUND":       14,
		"MARSHAL_TX_ERROR":             15,
		"NIL_TXACTION":                 16,
		"EXPIRED_CHAINCODE":            17,
		"CHAINCODE_VERSION_CONFLICT":   18,
		"BAD_HEADER_EXTENSION":         19,
		"BAD_CHANNEL_HEADER":           20,
		"BAD_RESPONSE_PAYLOAD":         21,
		"BAD_RWSET":                    22,
		"ILLEGAL_WRITESET":             23,
		"INVALID_WRITESET":             24,
		"INVALID_CHAINCODE":            25,
		"NOT_VALIDATED":                254,
		"INVALID_OTHER_REASON":         255,
	}
)

func (x TxValidationCode) Enum() *TxValidationCode {
	p := new(TxValidationCode)
	*p = x
	return p
}

func (x TxValidationCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxValidationCode) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_transaction_proto_enumTypes[0].Descriptor()
}

func (TxValidationCode) Type() protoreflect.EnumType {
	return &file_peer_transaction_proto_enumTypes[0]
}

func (x TxValidationCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxValidationCode.Descriptor instead.
func (TxValidationCode) EnumDescriptor() ([]byte, []int) {
	return file_peer_transaction_proto_rawDescGZIP(), []int{0}
}

// Reserved entries in the key-level metadata map
type MetaDataKeys int32

const (
	MetaDataKeys_VALIDATION_PARAMETER    MetaDataKeys = 0
	MetaDataKeys_VALIDATION_PARAMETER_V2 MetaDataKeys = 1
)

// Enum value maps for MetaDataKeys.
var (
	MetaDataKeys_name = map[int32]string{
		0: "VALIDATION_PARAMETER",
		1: "VALIDATION_PARAMETER_V2",
	}
	MetaDataKeys_value = map[string]int32{
		"VALIDATION_PARAMETER":    0,
		"VALIDATION_PARAMETER_V2": 1,
	}
)

func (x MetaDataKeys) Enum() *MetaDataKeys {
	p := new(MetaDataKeys)
	*p = x
	return p
}

func (x MetaDataKeys) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetaDataKeys) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_transaction_proto_enumTypes[1].Descriptor()
}

func (MetaDataKeys) Type() protoreflect.EnumType {
	return &file_peer_transaction_proto_enumTypes[1]
}

func (x MetaDataKeys) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetaDataKeys.Descriptor instead.
func (MetaDataKeys) EnumDescriptor() ([]byte, []int) {
	return file_peer_transaction_proto_rawDescGZIP(), []int{1}
}

// ProcessedTransaction wraps an Envelope that includes a transaction along with an indication
// of whether the transaction was validated or invalidated by committing peer.
// The use case is that GetTransactionByID API needs to retrieve the transaction Envelope
// from block storage, and return it to a client, and indicate whether the transaction
// was validated or invalidated by committing peer. So that the originally submitted
// transaction Envelope is not modified, the ProcessedTransaction wrapper is returned.
type ProcessedTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An Envelope which includes a processed transaction
	TransactionEnvelope *common.Envelope `protobuf:"bytes,1,opt,name=transactionEnvelope,proto3" json:"transactionEnvelope,omitempty"`
	// An indication of whether the transaction was validated or invalidated by committing peer
	ValidationCode int32 `protobuf:"varint,2,opt,name=validationCode,proto3" json:"validationCode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessedTransaction) Reset() {
	*x = ProcessedTransaction{}
	mi := &file_peer_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTransaction) ProtoMessage() {}

func (x *ProcessedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_peer_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTransaction.ProtoReflect.Descriptor instead.
func (*ProcessedTransaction) Descriptor() ([]byte, []int) {
	return file_peer_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessedTransaction) GetTransactionEnvelope() *common.Envelope {
	if x != nil {
		return x.TransactionEnvelope
	}
	return nil
}

func (x *ProcessedTransaction) GetValidationCode() int32 {
	if x != nil {
		return x.ValidationCode
	}
	return 0
}

// The transaction to be sent to the ordering service. A transaction contains
// one or more TransactionAction. Each TransactionAction binds a proposal to
// potentially multiple actions. The transaction is atomic meaning that either
// all actions in the transaction will be committed or none will.  Note that
// while a Transaction might include more than one Header, the Header.creator
// field must be the same in each.
// A single client is free to issue a number of independent Proposal, each with
// their header (Header) and request payload (ChaincodeProposalPayload).  Each
// proposal is independently endorsed generating an action
// (ProposalResponsePayload) with one signature per Endorser. Any number of
// independent proposals (and their action) might be included in a transaction
// to ensure that they are treated atomically.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payload is an array of TransactionAction. An array is necessary to
	// accommodate multiple actions per transaction
	Actions       []*TransactionAction `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_peer_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_peer_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_peer_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetActions() []*TransactionAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

// TransactionAction binds a proposal to its action.  The type field in the
// header dictates the type of action to be applied to the ledger.
type TransactionAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The header of the proposal action, which is the proposal header
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The payload of the action as defined by the type in the header For
	// chaincode, it's the bytes of ChaincodeActionPayload
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionAction) Reset() {
	*x = TransactionAction{}
	mi := &file_peer_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAction) ProtoMessage() {}

func (x *TransactionAction) ProtoReflect() protoreflect.Message {
	mi := &file_peer_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAction.ProtoReflect.Descriptor instead.
func (*TransactionAction) Descriptor() ([]byte, []int) {
	return file_peer_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionAction) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TransactionAction) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ChaincodeActionPayload is the message to be used for the TransactionAction's
// payload when the Header's type is set to CHAINCODE.  It carries the
// chaincodeProposalPayload and an endorsed action to apply to the ledger.
type ChaincodeActionPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field contains the bytes of the ChaincodeProposalPayload message from
	// the original invocation (essentially the arguments) after the application
	// of the visibility function. The main visibility modes are "full" (the
	// entire ChaincodeProposalPayload message is included here), "hash" (only
	// the hash of the ChaincodeProposalPayload message is included) or
	// "nothing".  This field will be used to check the consistency of
	// ProposalResponsePayload.proposalHash.  For the CHAINCODE type,
	// ProposalResponsePayload.proposalHash is supposed to be H(ProposalHeader ||
	// f(ChaincodeProposalPayload)) where f is the visibility function.
	ChaincodeProposalPayload []byte `protobuf:"bytes,1,opt,name=chaincode_proposal_payload,json=chaincodeProposalPayload,proto3" json:"chaincode_proposal_payload,omitempty"`
	// The list of actions to apply to the ledger
	Action        *ChaincodeEndorsedAction `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeActionPayload) Reset() {
	*x = ChaincodeActionPayload{}
	mi := &file_peer_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeActionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeActionPayload) ProtoMessage() {}

func (x *ChaincodeActionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_peer_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeActionPayload.ProtoReflect.Descriptor instead.
func (*ChaincodeActionPayload) Descriptor() ([]byte, []int) {
	return file_peer_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ChaincodeActionPayload) GetChaincodeProposalPayload() []byte {
	if x != nil {
		return x.ChaincodeProposalPayload
	}
	return nil
}

func (x *ChaincodeActionPayload) GetAction() *ChaincodeEndorsedAction {
	if x != nil {
		return x.Action
	}
	return nil
}

// ChaincodeEndorsedAction carries information about the endorsement of a
// specific proposal
type ChaincodeEndorsedAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the bytes of the ProposalResponsePayload message signed by the
	// endorsers.  Recall that for the CHAINCODE type, the
	// ProposalResponsePayload's extenstion field carries a ChaincodeAction
	ProposalResponsePayload []byte `protobuf:"bytes,1,opt,name=proposal_response_payload,json=proposalResponsePayload,proto3" json:"proposal_response_payload,omitempty"`
	// The endorsement of the proposal, basically the endorser's signature over
	// proposalResponsePayload
	Endorsements  []*Endorsement `protobuf:"bytes,2,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeEndorsedAction) Reset() {
	*x = ChaincodeEndorsedAction{}
	mi := &file_peer_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeEndorsedAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeEndorsedAction) ProtoMessage() {}

func (x *ChaincodeEndorsedAction) ProtoReflect() protoreflect.Message {
	mi := &file_peer_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeEndorsedAction.ProtoReflect.Descriptor instead.
func (*ChaincodeEndorsedAction) Descriptor() ([]byte, []int) {
	return file_peer_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *ChaincodeEndorsedAction) GetProposalResponsePayload() []byte {
	if x != nil {
		return x.ProposalResponsePayload
	}
	return nil
}

func (x *ChaincodeEndorsedAction) GetEndorsements() []*Endorsement {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

var File_peer_transaction_proto protoreflect.FileDescriptor

const file_peer_transaction_proto_rawDesc = "" +
	"\n" +
	"\x16peer/transaction.proto\x12\x06protos\x1a\x1cpeer/proposal_response.proto\x1a\x13common/common.proto\"\x82\x01\n" +
	"\x14ProcessedTransaction\x12B\n" +
	"\x13transactionEnvelope\x18\x01 \x01(\v2\x10.common.EnvelopeR\x13transactionEnvelope\x12&\n" +
	"\x0evalidationCode\x18\x02 \x01(\x05R\x0evalidationCode\"B\n" +
	"\vTransaction\x123\n" +
	"\aactions\x18\x01 \x03(\v2\x19.protos.TransactionActionR\aactions\"E\n" +
	"\x11TransactionAction\x12\x16\n" +
	"\x06header\x18\x01 \x01(\fR\x06header\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x8f\x01\n" +
	"\x16ChaincodeActionPayload\x12<\n" +
	"\x1achaincode_proposal_payload\x18\x01 \x01(\fR\x18chaincodeProposalPayload\x127\n" +
	"\x06action\x18\x02 \x01(\v2\x1f.protos.ChaincodeEndorsedActionR\x06action\"\x8e\x01\n" +
	"\x17ChaincodeEndorsedAction\x12:\n" +
	"\x19proposal_response_payload\x18\x01 \x01(\fR\x17proposalResponsePayload\x127\n" +
	"\fendorsements\x18\x02 \x03(\v2\x13.protos.EndorsementR\fendorsements*\xab\x05\n" +
	"\x10TxValidationCode\x12\t\n" +
	"\x05VALID\x10\x00\x12\x10\n" +
	"\fNIL_ENVELOPE\x10\x01\x12\x0f\n" +
	"\vBAD_PAYLOAD\x10\x02\x12\x15\n" +
	"\x11BAD_COMMON_HEADER\x10\x03\x12\x19\n" +
	"\x15BAD_CREATOR_SIGNATURE\x10\x04\x12 \n" +
	"\x1cINVALID_ENDORSER_TRANSACTION\x10\x05\x12\x1e\n" +
	"\x1aINVALID_CONFIG_TRANSACTION\x10\x06\x12\x1a\n" +
	"\x16UNSUPPORTED_TX_PAYLOAD\x10\a\x12\x15\n" +
	"\x11BAD_PROPOSAL_TXID\x10\b\x12\x12\n" +
	"\x0eDUPLICATE_TXID\x10\t\x12\x1e\n" +
	"\x1aENDORSEMENT_POLICY_FAILURE\x10\n" +
	"\x12\x16\n" +
	"\x12MVCC_READ_CONFLICT\x10\v\x12\x19\n" +
	"\x15PHANTOM_READ_CONFLICT\x10\f\x12\x13\n" +
	"\x0fUNKNOWN_TX_TYPE\x10\r\x12\x1a\n" +
	"\x16TARGET_CHAIN_NOT_FOUND\x10\x0e\x12\x14\n" +
	"\x10MARSHAL_TX_ERROR\x10\x0f\x12\x10\n" +
	"\fNIL_TXACTION\x10\x10\x12\x15\n" +
	"\x11EXPIRED_CHAINCODE\x10\x11\x12\x1e\n" +
	"\x1aCHAINCODE_VERSION_CONFLICT\x10\x12\x12\x18\n" +
	"\x14BAD_HEADER_EXTENSION\x10\x13\x12\x16\n" +
	"\x12BAD_CHANNEL_HEADER\x10\x14\x12\x18\n" +
	"\x14BAD_RESPONSE_PAYLOAD\x10\x15\x12\r\n" +
	"\tBAD_RWSET\x10\x16\x12\x14\n" +
	"\x10ILLEGAL_WRITESET\x10\x17\x12\x14\n" +
	"\x10INVALID_WRITESET\x10\x18\x12\x15\n" +
	"\x11INVALID_CHAINCODE\x10\x19\x12\x12\n" +
	"\rNOT_VALIDATED\x10\xfe\x01\x12\x19\n" +
	"\x14INVALID_OTHER_REASON\x10\xff\x01*E\n" +
	"\fMetaDataKeys\x12\x18\n" +
	"\x14VALIDATION_PARAMETER\x10\x00\x12\x1b\n" +
	"\x17VALIDATION_PARAMETER_V2\x10\x01Bf\n" +
	"\"org.hyperledger.fabric.protos.peerB\x12TransactionPackageZ,github.com/hyperledger/fabric-protos-go/peerb\x06proto3"

var (
	file_peer_transaction_proto_rawDescOnce sync.Once
	file_peer_transaction_proto_rawDescData []byte
)

func file_peer_transaction_proto_rawDescGZIP() []byte {
	file_peer_transaction_proto_rawDescOnce.Do(func() {
		file_peer_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_transaction_proto_rawDesc), len(file_peer_transaction_proto_rawDesc)))
	})
	return file_peer_transaction_proto_rawDescData
}

var file_peer_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_peer_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_peer_transaction_proto_goTypes = []any{
	(TxValidationCode)(0),           // 0: protos.TxValidationCode
	(MetaDataKeys)(0),               // 1: protos.MetaDataKeys
	(*ProcessedTransaction)(nil),    // 2: protos.ProcessedTransaction
	(*Transaction)(nil),             // 3: protos.Transaction
	(*TransactionAction)(nil),       // 4: protos.TransactionAction
	(*ChaincodeActionPayload)(nil),  // 5: protos.ChaincodeActionPayload
	(*ChaincodeEndorsedAction)(nil), // 6: protos.ChaincodeEndorsedAction
	(*common.Envelope)(nil),         // 7: common.Envelope
	(*Endorsement)(nil),             // 8: protos.Endorsement
}
var file_peer_transaction_proto_depIdxs = []int32{
	7, // 0: protos.ProcessedTransaction.transactionEnvelope:type_name -> common.Envelope
	4, // 1: protos.Transaction.actions:type_name -> protos.TransactionAction
	6, // 2: protos.ChaincodeActionPayload.action:type_name -> protos.ChaincodeEndorsedAction
	8, // 3: protos.ChaincodeEndorsedAction.endorsements:type_name -> protos.Endorsement
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_peer_transaction_proto_init() }
func file_peer_transaction_proto_init() {
	if File_peer_transaction_proto != nil {
		return
	}
	file_peer_proposal_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_transaction_proto_rawDesc), len(file_peer_transaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_transaction_proto_goTypes,
		DependencyIndexes: file_peer_transaction_proto_depIdxs,
		EnumInfos:         file_peer_transaction_proto_enumTypes,
		MessageInfos:      file_peer_transaction_proto_msgTypes,
	}.Build()
	File_peer_transaction_proto = out.File
	file_peer_transaction_proto_goTypes = nil
	file_peer_transaction_proto_depIdxs = nil
}
