// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ledger/rwset/rwset.proto

package rwset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxReadWriteSet_DataModel int32

const (
	TxReadWriteSet_KV TxReadWriteSet_DataModel = 0
)

// Enum value maps for TxReadWriteSet_DataModel.
var (
	TxReadWriteSet_DataModel_name = map[int32]string{
		0: "KV",
	}
	TxReadWriteSet_DataModel_value = map[string]int32{
		"KV": 0,
	}
)

func (x TxReadWriteSet_DataModel) Enum() *TxReadWriteSet_DataModel {
	p := new(TxReadWriteSet_DataModel)
	*p = x
	return p
}

func (x TxReadWriteSet_DataModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxReadWriteSet_DataModel) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_rwset_rwset_proto_enumTypes[0].Descriptor()
}

func (TxReadWriteSet_DataModel) Type() protoreflect.EnumType {
	return &file_ledger_rwset_rwset_proto_enumTypes[0]
}

func (x TxReadWriteSet_DataModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxReadWriteSet_DataModel.Descriptor instead.
func (TxReadWriteSet_DataModel) EnumDescriptor() ([]byte, []int) {
	return file_ledger_rwset_rwset_proto_rawDescGZIP(), []int{0, 0}
}

// TxReadWriteSet encapsulates a read-write set for a transaction
// DataModel specifies the enum value of the data model
// ns_rwset field specifies a list of chaincode specific read-write set (one for each chaincode)
type TxReadWriteSet struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DataModel     TxReadWriteSet_DataModel `protobuf:"varint,1,opt,name=data_model,json=dataModel,proto3,enum=rwset.TxReadWriteSet_DataModel" json:"data_model,omitempty"`
	NsRwset       []*NsReadWriteSet        `protobuf:"bytes,2,rep,name=ns_rwset,json=nsRwset,proto3" json:"ns_rwset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxReadWriteSet) Reset() {
	*x = TxReadWriteSet{}
	mi := &file_ledger_rwset_rwset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxReadWriteSet) ProtoMessage() {}

func (x *TxReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_rwset_rwset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxReadWriteSet.ProtoReflect.Descriptor instead.
func (*TxReadWriteSet) Descriptor() ([]byte, []int) {
	return file_ledger_rwset_rwset_proto_rawDescGZIP(), []int{0}
}

func (x *TxReadWriteSet) GetDataModel() TxReadWriteSet_DataModel {
	if x != nil {
		return x.DataModel
	}
	return TxReadWriteSet_KV
}

func (x *TxReadWriteSet) GetNsRwset() []*NsReadWriteSet {
	if x != nil {
		return x.NsRwset
	}
	return nil
}

// NsReadWriteSet encapsulates the read-write set for a chaincode
type NsReadWriteSet struct {
	state                 protoimpl.MessageState          `protogen:"open.v1"`
	Namespace             string                          `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Rwset                 []byte                          `protobuf:"bytes,2,opt,name=rwset,proto3" json:"rwset,omitempty"` // Data model specific serialized proto message (e.g., kvrwset.KVRWSet for KV and Document data models)
	CollectionHashedRwset []*CollectionHashedReadWriteSet `protobuf:"bytes,3,rep,name=collection_hashed_rwset,json=collectionHashedRwset,proto3" json:"collection_hashed_rwset,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NsReadWriteSet) Reset() {
	*x = NsReadWriteSet{}
	mi := &file_ledger_rwset_rwset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsReadWriteSet) ProtoMessage() {}

func (x *NsReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_rwset_rwset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsReadWriteSet.ProtoReflect.Descriptor instead.
func (*NsReadWriteSet) Descriptor() ([]byte, []int) {
	return file_ledger_rwset_rwset_proto_rawDescGZIP(), []int{1}
}

func (x *NsReadWriteSet) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NsReadWriteSet) GetRwset() []byte {
	if x != nil {
		return x.Rwset
	}
	return nil
}

func (x *NsReadWriteSet) GetCollectionHashedRwset() []*CollectionHashedReadWriteSet {
	if x != nil {
		return x.CollectionHashedRwset
	}
	return nil
}

// CollectionHashedReadWriteSet encapsulate the hashed representation for the private read-write set for a collection
type CollectionHashedReadWriteSet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	HashedRwset    []byte                 `protobuf:"bytes,2,opt,name=hashed_rwset,json=hashedRwset,proto3" json:"hashed_rwset,omitempty"`      // Data model specific serialized proto message (e.g., kvrwset.HashedRWSet for KV and Document data models)
	PvtRwsetHash   []byte                 `protobuf:"bytes,3,opt,name=pvt_rwset_hash,json=pvtRwsetHash,proto3" json:"pvt_rwset_hash,omitempty"` // Hash of entire private read-write set for a specific collection. This helps in authenticating the private read-write set efficiently
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionHashedReadWriteSet) Reset() {
	*x = CollectionHashedReadWriteSet{}
	mi := &file_ledger_rwset_rwset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionHashedReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionHashedReadWriteSet) ProtoMessage() {}

func (x *CollectionHashedReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_rwset_rwset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionHashedReadWriteSet.ProtoReflect.Descriptor instead.
func (*CollectionHashedReadWriteSet) Descriptor() ([]byte, []int) {
	return file_ledger_rwset_rwset_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionHashedReadWriteSet) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionHashedReadWriteSet) GetHashedRwset() []byte {
	if x != nil {
		return x.HashedRwset
	}
	return nil
}

func (x *CollectionHashedReadWriteSet) GetPvtRwsetHash() []byte {
	if x != nil {
		return x.PvtRwsetHash
	}
	return nil
}

// TxPvtReadWriteSet encapsulate the private read-write set for a transaction
type TxPvtReadWriteSet struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DataModel     TxReadWriteSet_DataModel `protobuf:"varint,1,opt,name=data_model,json=dataModel,proto3,enum=rwset.TxReadWriteSet_DataModel" json:"data_model,omitempty"`
	NsPvtRwset    []*NsPvtReadWriteSet     `protobuf:"bytes,2,rep,name=ns_pvt_rwset,json=nsPvtRwset,proto3" json:"ns_pvt_rwset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxPvtReadWriteSet) Reset() {
	*x = TxPvtReadWriteSet{}
	mi := &file_ledger_rwset_rwset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxPvtReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPvtReadWriteSet) ProtoMessage() {}

func (x *TxPvtReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_rwset_rwset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPvtReadWriteSet.ProtoReflect.Descriptor instead.
func (*TxPvtReadWriteSet) Descriptor() ([]byte, []int) {
	return file_ledger_rwset_rwset_proto_rawDescGZIP(), []int{3}
}

func (x *TxPvtReadWriteSet) GetDataModel() TxReadWriteSet_DataModel {
	if x != nil {
		return x.DataModel
	}
	return TxReadWriteSet_KV
}

func (x *TxPvtReadWriteSet) GetNsPvtRwset() []*NsPvtReadWriteSet {
	if x != nil {
		return x.NsPvtRwset
	}
	return nil
}

// NsPvtReadWriteSet encapsulates the private read-write set for a chaincode
type NsPvtReadWriteSet struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	Namespace          string                       `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CollectionPvtRwset []*CollectionPvtReadWriteSet `protobuf:"bytes,2,rep,name=collection_pvt_rwset,json=collectionPvtRwset,proto3" json:"collection_pvt_rwset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NsPvtReadWriteSet) Reset() {
	*x = NsPvtReadWriteSet{}
	mi := &file_ledger_rwset_rwset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsPvtReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsPvtReadWriteSet) ProtoMessage() {}

func (x *NsPvtReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_rwset_rwset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsPvtReadWriteSet.ProtoReflect.Descriptor instead.
func (*NsPvtReadWriteSet) Descriptor() ([]byte, []int) {
	return file_ledger_rwset_rwset_proto_rawDescGZIP(), []int{4}
}

func (x *NsPvtReadWriteSet) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NsPvtReadWriteSet) GetCollectionPvtRwset() []*CollectionPvtReadWriteSet {
	if x != nil {
		return x.CollectionPvtRwset
	}
	return nil
}

// CollectionPvtReadWriteSet encapsulates the private read-write set for a collection
type CollectionPvtReadWriteSet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Rwset          []byte                 `protobuf:"bytes,2,opt,name=rwset,proto3" json:"rwset,omitempty"` // Data model specific serialized proto message (e.g., kvrwset.KVRWSet for KV and Document data models)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionPvtReadWriteSet) Reset() {
	*x = CollectionPvtReadWriteSet{}
	mi := &file_ledger_rwset_rwset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionPvtReadWriteSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionPvtReadWriteSet) ProtoMessage() {}

func (x *CollectionPvtReadWriteSet) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_rwset_rwset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionPvtReadWriteSet.ProtoReflect.Descriptor instead.
func (*CollectionPvtReadWriteSet) Descriptor() ([]byte, []int) {
	return file_ledger_rwset_rwset_proto_rawDescGZIP(), []int{5}
}

func (x *CollectionPvtReadWriteSet) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionPvtReadWriteSet) GetRwset() []byte {
	if x != nil {
		return x.Rwset
	}
	return nil
}

var File_ledger_rwset_rwset_proto protoreflect.FileDescriptor

const file_ledger_rwset_rwset_proto_rawDesc = "" +
	"\n" +
	"\x18ledger/rwset/rwset.proto\x12\x05rwset\"\x97\x01\n" +
	"\x0eTxReadWriteSet\x12>\n" +
	"\n" +
	"data_model\x18\x01 \x01(\x0e2\x1f.rwset.TxReadWriteSet.DataModelR\tdataModel\x120\n" +
	"\bns_rwset\x18\x02 \x03(\v2\x15.rwset.NsReadWriteSetR\ansRwset\"\x13\n" +
	"\tDataModel\x12\x06\n" +
	"\x02KV\x10\x00\"\xa1\x01\n" +
	"\x0eNsReadWriteSet\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05rwset\x18\x02 \x01(\fR\x05rwset\x12[\n" +
	"\x17collection_hashed_rwset\x18\x03 \x03(\v2#.rwset.CollectionHashedReadWriteSetR\x15collectionHashedRwset\"\x90\x01\n" +
	"\x1cCollectionHashedReadWriteSet\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12!\n" +
	"\fhashed_rwset\x18\x02 \x01(\fR\vhashedRwset\x12$\n" +
	"\x0epvt_rwset_hash\x18\x03 \x01(\fR\fpvtRwsetHash\"\x8f\x01\n" +
	"\x11TxPvtReadWriteSet\x12>\n" +
	"\n" +
	"data_model\x18\x01 \x01(\x0e2\x1f.rwset.TxReadWriteSet.DataModelR\tdataModel\x12:\n" +
	"\fns_pvt_rwset\x18\x02 \x03(\v2\x18.rwset.NsPvtReadWriteSetR\n" +
	"nsPvtRwset\"\x85\x01\n" +
	"\x11NsPvtReadWriteSet\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12R\n" +
	"\x14collection_pvt_rwset\x18\x02 \x03(\v2 .rwset.CollectionPvtReadWriteSetR\x12collectionPvtRwset\"Z\n" +
	"\x19CollectionPvtReadWriteSet\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x14\n" +
	"\x05rwset\x18\x02 \x01(\fR\x05rwsetBb\n" +
	"*org.hyperledger.fabric.protos.ledger.rwsetZ4github.com/hyperledger/fabric-protos-go/ledger/rwsetb\x06proto3"

var (
	file_ledger_rwset_rwset_proto_rawDescOnce sync.Once
	file_ledger_rwset_rwset_proto_rawDescData []byte
)

func file_ledger_rwset_rwset_proto_rawDescGZIP() []byte {
	file_ledger_rwset_rwset_proto_rawDescOnce.Do(func() {
		file_ledger_rwset_rwset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_rwset_rwset_proto_rawDesc), len(file_ledger_rwset_rwset_proto_rawDesc)))
	})
	return file_ledger_rwset_rwset_proto_rawDescData
}

var file_ledger_rwset_rwset_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ledger_rwset_rwset_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ledger_rwset_rwset_proto_goTypes = []any{
	(TxReadWriteSet_DataModel)(0),        // 0: rwset.TxReadWriteSet.DataModel
	(*TxReadWriteSet)(nil),               // 1: rwset.TxReadWriteSet
	(*NsReadWriteSet)(nil),               // 2: rwset.NsReadWriteSet
	(*CollectionHashedReadWriteSet)(nil), // 3: rwset.CollectionHashedReadWriteSet
	(*TxPvtReadWriteSet)(nil),            // 4: rwset.TxPvtReadWriteSet
	(*NsPvtReadWriteSet)(nil),            // 5: rwset.NsPvtReadWriteSet
	(*CollectionPvtReadWriteSet)(nil),    // 6: rwset.CollectionPvtReadWriteSet
}
var file_ledger_rwset_rwset_proto_depIdxs = []int32{
	0, // 0: rwset.TxReadWriteSet.data_model:type_name -> rwset.TxReadWriteSet.DataModel
	2, // 1: rwset.TxReadWriteSet.ns_rwset:type_name -> rwset.NsReadWriteSet
	3, // 2: rwset.NsReadWriteSet.collection_hashed_rwset:type_name -> rwset.CollectionHashedReadWriteSet
	0, // 3: rwset.TxPvtReadWriteSet.data_model:type_name -> rwset.TxReadWriteSet.DataModel
	5, // 4: rwset.TxPvtReadWriteSet.ns_pvt_rwset:type_name -> rwset.NsPvtReadWriteSet
	6, // 5: rwset.NsPvtReadWriteSet.collection_pvt_rwset:type_name -> rwset.CollectionPvtReadWriteSet
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ledger_rwset_rwset_proto_init() }
func file_ledger_rwset_rwset_proto_init() {
	if File_ledger_rwset_rwset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_rwset_rwset_proto_rawDesc), len(file_ledger_rwset_rwset_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledger_rwset_rwset_proto_goTypes,
		DependencyIndexes: file_ledger_rwset_rwset_proto_depIdxs,
		EnumInfos:         file_ledger_rwset_rwset_proto_enumTypes,
		MessageInfos:      file_ledger_rwset_rwset_proto_msgTypes,
	}.Build()
	File_ledger_rwset_rwset_proto = out.File
	file_ledger_rwset_rwset_proto_goTypes = nil
	file_ledger_rwset_rwset_proto_depIdxs = nil
}
