// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: common/configuration.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HashingAlgorithm is encoded into the configuration transaction as a
// configuration item of type Chain with a Key of "HashingAlgorithm" and a
// Value of HashingAlgorithm as marshaled protobuf bytes
type HashingAlgorithm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA256 is currently the only supported and tested algorithm.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashingAlgorithm) Reset() {
	*x = HashingAlgorithm{}
	mi := &file_common_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashingAlgorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashingAlgorithm) ProtoMessage() {}

func (x *HashingAlgorithm) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashingAlgorithm.ProtoReflect.Descriptor instead.
func (*HashingAlgorithm) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *HashingAlgorithm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// BlockDataHashingStructure is encoded into the configuration transaction as a configuration item of
// type Chain with a Key of "BlockDataHashingStructure" and a Value of HashingAlgorithm as marshaled protobuf bytes
type BlockDataHashingStructure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// width specifies the width of the Merkle tree to use when computing the BlockDataHash
	// in order to replicate flat hashing, set this width to MAX_UINT32
	Width         uint32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDataHashingStructure) Reset() {
	*x = BlockDataHashingStructure{}
	mi := &file_common_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDataHashingStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDataHashingStructure) ProtoMessage() {}

func (x *BlockDataHashingStructure) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDataHashingStructure.ProtoReflect.Descriptor instead.
func (*BlockDataHashingStructure) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *BlockDataHashingStructure) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

// OrdererAddresses is encoded into the configuration transaction as a configuration item of type Chain
// with a Key of "OrdererAddresses" and a Value of OrdererAddresses as marshaled protobuf bytes
type OrdererAddresses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdererAddresses) Reset() {
	*x = OrdererAddresses{}
	mi := &file_common_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdererAddresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdererAddresses) ProtoMessage() {}

func (x *OrdererAddresses) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdererAddresses.ProtoReflect.Descriptor instead.
func (*OrdererAddresses) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *OrdererAddresses) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	MspId         string                 `protobuf:"bytes,4,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	Identity      []byte                 `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	ClientTlsCert []byte                 `protobuf:"bytes,6,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert []byte                 `protobuf:"bytes,7,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consenter) Reset() {
	*x = Consenter{}
	mi := &file_common_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consenter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consenter) ProtoMessage() {}

func (x *Consenter) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consenter.ProtoReflect.Descriptor instead.
func (*Consenter) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *Consenter) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Consenter) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Consenter) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Consenter) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

func (x *Consenter) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Consenter) GetClientTlsCert() []byte {
	if x != nil {
		return x.ClientTlsCert
	}
	return nil
}

func (x *Consenter) GetServerTlsCert() []byte {
	if x != nil {
		return x.ServerTlsCert
	}
	return nil
}

// Orderers is encoded into the configuration transaction as a configuration item of type Chain
// with a Key of "Orderers" and a Value of Orderers as marshaled protobuf bytes
type Orderers struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConsenterMapping []*Consenter           `protobuf:"bytes,1,rep,name=consenter_mapping,json=consenterMapping,proto3" json:"consenter_mapping,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Orderers) Reset() {
	*x = Orderers{}
	mi := &file_common_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orderers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orderers) ProtoMessage() {}

func (x *Orderers) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orderers.ProtoReflect.Descriptor instead.
func (*Orderers) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *Orderers) GetConsenterMapping() []*Consenter {
	if x != nil {
		return x.ConsenterMapping
	}
	return nil
}

// Consortium represents the consortium context in which the channel was created
type Consortium struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consortium) Reset() {
	*x = Consortium{}
	mi := &file_common_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consortium) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consortium) ProtoMessage() {}

func (x *Consortium) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consortium.ProtoReflect.Descriptor instead.
func (*Consortium) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *Consortium) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Capabilities message defines the capabilities a particular binary must implement
// for that binary to be able to safely participate in the channel.  The capabilities
// message is defined at the /Channel level, the /Channel/Application level, and the
// /Channel/Orderer level.
//
// The /Channel level capabilties define capabilities which both the orderer and peer
// binaries must satisfy.  These capabilties might be things like a new MSP type,
// or a new policy type.
//
// The /Channel/Orderer level capabilties define capabilities which must be supported
// by the orderer, but which have no bearing on the behavior of the peer.  For instance
// if the orderer changes the logic for how it constructs new channels, only all orderers
// must agree on the new logic.  The peers do not need to be aware of this change as
// they only interact with the channel after it has been constructed.
//
// Finally, the /Channel/Application level capabilities define capabilities which the peer
// binary must satisfy, but which have no bearing on the orderer.  For instance, if the
// peer adds a new UTXO transaction type, or changes the chaincode lifecycle requirements,
// all peers must agree on the new logic.  However, orderers never inspect transactions
// this deeply, and therefore have no need to be aware of the change.
//
// The capabilities strings defined in these messages typically correspond to release
// binary versions (e.g. "V1.1"), and are used primarilly as a mechanism for a fully
// upgraded network to switch from one set of logic to a new one.
//
// Although for V1.1, the orderers must be upgraded to V1.1 prior to the rest of the
// network, going forward, because of the split between the /Channel, /Channel/Orderer
// and /Channel/Application capabilities.  It should be possible for the orderer and
// application networks to upgrade themselves independently (with the exception of any
// new capabilities defined at the /Channel level).
type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  map[string]*Capability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_common_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{6}
}

func (x *Capabilities) GetCapabilities() map[string]*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Capability is an empty message for the time being.  It is defined as a protobuf
// message rather than a constant, so that we may extend capabilities with other fields
// if the need arises in the future.  For the time being, a capability being in the
// capabilities map requires that that capability be supported.
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_common_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_common_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_common_configuration_proto_rawDescGZIP(), []int{7}
}

var File_common_configuration_proto protoreflect.FileDescriptor

const file_common_configuration_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/configuration.proto\x12\x06common\"&\n" +
	"\x10HashingAlgorithm\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x19BlockDataHashingStructure\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\"0\n" +
	"\x10OrdererAddresses\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"\xc6\x01\n" +
	"\tConsenter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x15\n" +
	"\x06msp_id\x18\x04 \x01(\tR\x05mspId\x12\x1a\n" +
	"\bidentity\x18\x05 \x01(\fR\bidentity\x12&\n" +
	"\x0fclient_tls_cert\x18\x06 \x01(\fR\rclientTlsCert\x12&\n" +
	"\x0fserver_tls_cert\x18\a \x01(\fR\rserverTlsCert\"J\n" +
	"\bOrderers\x12>\n" +
	"\x11consenter_mapping\x18\x01 \x03(\v2\x11.common.ConsenterR\x10consenterMapping\" \n" +
	"\n" +
	"Consortium\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xaf\x01\n" +
	"\fCapabilities\x12J\n" +
	"\fcapabilities\x18\x01 \x03(\v2&.common.Capabilities.CapabilitiesEntryR\fcapabilities\x1aS\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.common.CapabilityR\x05value:\x028\x01\"\f\n" +
	"\n" +
	"CapabilityBV\n" +
	"$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/commonb\x06proto3"

var (
	file_common_configuration_proto_rawDescOnce sync.Once
	file_common_configuration_proto_rawDescData []byte
)

func file_common_configuration_proto_rawDescGZIP() []byte {
	file_common_configuration_proto_rawDescOnce.Do(func() {
		file_common_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_configuration_proto_rawDesc), len(file_common_configuration_proto_rawDesc)))
	})
	return file_common_configuration_proto_rawDescData
}

var file_common_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_configuration_proto_goTypes = []any{
	(*HashingAlgorithm)(nil),          // 0: common.HashingAlgorithm
	(*BlockDataHashingStructure)(nil), // 1: common.BlockDataHashingStructure
	(*OrdererAddresses)(nil),          // 2: common.OrdererAddresses
	(*Consenter)(nil),                 // 3: common.Consenter
	(*Orderers)(nil),                  // 4: common.Orderers
	(*Consortium)(nil),                // 5: common.Consortium
	(*Capabilities)(nil),              // 6: common.Capabilities
	(*Capability)(nil),                // 7: common.Capability
	nil,                               // 8: common.Capabilities.CapabilitiesEntry
}
var file_common_configuration_proto_depIdxs = []int32{
	3, // 0: common.Orderers.consenter_mapping:type_name -> common.Consenter
	8, // 1: common.Capabilities.capabilities:type_name -> common.Capabilities.CapabilitiesEntry
	7, // 2: common.Capabilities.CapabilitiesEntry.value:type_name -> common.Capability
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_configuration_proto_init() }
func file_common_configuration_proto_init() {
	if File_common_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_configuration_proto_rawDesc), len(file_common_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_configuration_proto_goTypes,
		DependencyIndexes: file_common_configuration_proto_depIdxs,
		MessageInfos:      file_common_configuration_proto_msgTypes,
	}.Build()
	File_common_configuration_proto = out.File
	file_common_configuration_proto_goTypes = nil
	file_common_configuration_proto_depIdxs = nil
}
