// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: common/ledger.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contains information about the blockchain ledger such as height, current
// block hash, and previous block hash.
type BlockchainInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Height            uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	CurrentBlockHash  []byte                 `protobuf:"bytes,2,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	PreviousBlockHash []byte                 `protobuf:"bytes,3,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
	// Specifies bootstrapping snapshot info if the channel is bootstrapped from a snapshot.
	// It is nil if the channel is not bootstrapped from a snapshot.
	BootstrappingSnapshotInfo *BootstrappingSnapshotInfo `protobuf:"bytes,4,opt,name=bootstrappingSnapshotInfo,proto3" json:"bootstrappingSnapshotInfo,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *BlockchainInfo) Reset() {
	*x = BlockchainInfo{}
	mi := &file_common_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainInfo) ProtoMessage() {}

func (x *BlockchainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainInfo.ProtoReflect.Descriptor instead.
func (*BlockchainInfo) Descriptor() ([]byte, []int) {
	return file_common_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainInfo) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockchainInfo) GetCurrentBlockHash() []byte {
	if x != nil {
		return x.CurrentBlockHash
	}
	return nil
}

func (x *BlockchainInfo) GetPreviousBlockHash() []byte {
	if x != nil {
		return x.PreviousBlockHash
	}
	return nil
}

func (x *BlockchainInfo) GetBootstrappingSnapshotInfo() *BootstrappingSnapshotInfo {
	if x != nil {
		return x.BootstrappingSnapshotInfo
	}
	return nil
}

// Contains information for the bootstrapping snapshot.
type BootstrappingSnapshotInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LastBlockInSnapshot uint64                 `protobuf:"varint,1,opt,name=lastBlockInSnapshot,proto3" json:"lastBlockInSnapshot,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BootstrappingSnapshotInfo) Reset() {
	*x = BootstrappingSnapshotInfo{}
	mi := &file_common_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrappingSnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrappingSnapshotInfo) ProtoMessage() {}

func (x *BootstrappingSnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrappingSnapshotInfo.ProtoReflect.Descriptor instead.
func (*BootstrappingSnapshotInfo) Descriptor() ([]byte, []int) {
	return file_common_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrappingSnapshotInfo) GetLastBlockInSnapshot() uint64 {
	if x != nil {
		return x.LastBlockInSnapshot
	}
	return 0
}

var File_common_ledger_proto protoreflect.FileDescriptor

const file_common_ledger_proto_rawDesc = "" +
	"\n" +
	"\x13common/ledger.proto\x12\x06common\"\xe3\x01\n" +
	"\x0eBlockchainInfo\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12*\n" +
	"\x10currentBlockHash\x18\x02 \x01(\fR\x10currentBlockHash\x12,\n" +
	"\x11previousBlockHash\x18\x03 \x01(\fR\x11previousBlockHash\x12_\n" +
	"\x19bootstrappingSnapshotInfo\x18\x04 \x01(\v2!.common.BootstrappingSnapshotInfoR\x19bootstrappingSnapshotInfo\"M\n" +
	"\x19BootstrappingSnapshotInfo\x120\n" +
	"\x13lastBlockInSnapshot\x18\x01 \x01(\x04R\x13lastBlockInSnapshotBV\n" +
	"$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/commonb\x06proto3"

var (
	file_common_ledger_proto_rawDescOnce sync.Once
	file_common_ledger_proto_rawDescData []byte
)

func file_common_ledger_proto_rawDescGZIP() []byte {
	file_common_ledger_proto_rawDescOnce.Do(func() {
		file_common_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_ledger_proto_rawDesc), len(file_common_ledger_proto_rawDesc)))
	})
	return file_common_ledger_proto_rawDescData
}

var file_common_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_ledger_proto_goTypes = []any{
	(*BlockchainInfo)(nil),            // 0: common.BlockchainInfo
	(*BootstrappingSnapshotInfo)(nil), // 1: common.BootstrappingSnapshotInfo
}
var file_common_ledger_proto_depIdxs = []int32{
	1, // 0: common.BlockchainInfo.bootstrappingSnapshotInfo:type_name -> common.BootstrappingSnapshotInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_ledger_proto_init() }
func file_common_ledger_proto_init() {
	if File_common_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_ledger_proto_rawDesc), len(file_common_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_ledger_proto_goTypes,
		DependencyIndexes: file_common_ledger_proto_depIdxs,
		MessageInfos:      file_common_ledger_proto_msgTypes,
	}.Build()
	File_common_ledger_proto = out.File
	file_common_ledger_proto_goTypes = nil
	file_common_ledger_proto_depIdxs = nil
}
