// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: orderer/etcdraft/configuration.proto

package etcdraft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "etcdraft".
type ConfigMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consenters    []*Consenter           `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options       *Options               `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMetadata) Reset() {
	*x = ConfigMetadata{}
	mi := &file_orderer_etcdraft_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMetadata) ProtoMessage() {}

func (x *ConfigMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orderer_etcdraft_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMetadata.ProtoReflect.Descriptor instead.
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return file_orderer_etcdraft_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMetadata) GetConsenters() []*Consenter {
	if x != nil {
		return x.Consenters
	}
	return nil
}

func (x *ConfigMetadata) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ClientTlsCert []byte                 `protobuf:"bytes,3,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert []byte                 `protobuf:"bytes,4,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consenter) Reset() {
	*x = Consenter{}
	mi := &file_orderer_etcdraft_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consenter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consenter) ProtoMessage() {}

func (x *Consenter) ProtoReflect() protoreflect.Message {
	mi := &file_orderer_etcdraft_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consenter.ProtoReflect.Descriptor instead.
func (*Consenter) Descriptor() ([]byte, []int) {
	return file_orderer_etcdraft_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *Consenter) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Consenter) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Consenter) GetClientTlsCert() []byte {
	if x != nil {
		return x.ClientTlsCert
	}
	return nil
}

func (x *Consenter) GetServerTlsCert() []byte {
	if x != nil {
		return x.ServerTlsCert
	}
	return nil
}

// Options to be specified for all the etcd/raft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TickInterval      string                 `protobuf:"bytes,1,opt,name=tick_interval,json=tickInterval,proto3" json:"tick_interval,omitempty"` // time duration format, e.g. 500ms
	ElectionTick      uint32                 `protobuf:"varint,2,opt,name=election_tick,json=electionTick,proto3" json:"election_tick,omitempty"`
	HeartbeatTick     uint32                 `protobuf:"varint,3,opt,name=heartbeat_tick,json=heartbeatTick,proto3" json:"heartbeat_tick,omitempty"`
	MaxInflightBlocks uint32                 `protobuf:"varint,4,opt,name=max_inflight_blocks,json=maxInflightBlocks,proto3" json:"max_inflight_blocks,omitempty"`
	// Take snapshot when cumulative data exceeds certain size in bytes.
	SnapshotIntervalSize uint32 `protobuf:"varint,5,opt,name=snapshot_interval_size,json=snapshotIntervalSize,proto3" json:"snapshot_interval_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_orderer_etcdraft_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_orderer_etcdraft_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_orderer_etcdraft_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *Options) GetTickInterval() string {
	if x != nil {
		return x.TickInterval
	}
	return ""
}

func (x *Options) GetElectionTick() uint32 {
	if x != nil {
		return x.ElectionTick
	}
	return 0
}

func (x *Options) GetHeartbeatTick() uint32 {
	if x != nil {
		return x.HeartbeatTick
	}
	return 0
}

func (x *Options) GetMaxInflightBlocks() uint32 {
	if x != nil {
		return x.MaxInflightBlocks
	}
	return 0
}

func (x *Options) GetSnapshotIntervalSize() uint32 {
	if x != nil {
		return x.SnapshotIntervalSize
	}
	return 0
}

var File_orderer_etcdraft_configuration_proto protoreflect.FileDescriptor

const file_orderer_etcdraft_configuration_proto_rawDesc = "" +
	"\n" +
	"$orderer/etcdraft/configuration.proto\x12\betcdraft\"r\n" +
	"\x0eConfigMetadata\x123\n" +
	"\n" +
	"consenters\x18\x01 \x03(\v2\x13.etcdraft.ConsenterR\n" +
	"consenters\x12+\n" +
	"\aoptions\x18\x02 \x01(\v2\x11.etcdraft.OptionsR\aoptions\"\x83\x01\n" +
	"\tConsenter\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12&\n" +
	"\x0fclient_tls_cert\x18\x03 \x01(\fR\rclientTlsCert\x12&\n" +
	"\x0fserver_tls_cert\x18\x04 \x01(\fR\rserverTlsCert\"\xe0\x01\n" +
	"\aOptions\x12#\n" +
	"\rtick_interval\x18\x01 \x01(\tR\ftickInterval\x12#\n" +
	"\relection_tick\x18\x02 \x01(\rR\felectionTick\x12%\n" +
	"\x0eheartbeat_tick\x18\x03 \x01(\rR\rheartbeatTick\x12.\n" +
	"\x13max_inflight_blocks\x18\x04 \x01(\rR\x11maxInflightBlocks\x124\n" +
	"\x16snapshot_interval_size\x18\x05 \x01(\rR\x14snapshotIntervalSizeBj\n" +
	".org.hyperledger.fabric.protos.orderer.etcdraftZ8github.com/hyperledger/fabric-protos-go/orderer/etcdraftb\x06proto3"

var (
	file_orderer_etcdraft_configuration_proto_rawDescOnce sync.Once
	file_orderer_etcdraft_configuration_proto_rawDescData []byte
)

func file_orderer_etcdraft_configuration_proto_rawDescGZIP() []byte {
	file_orderer_etcdraft_configuration_proto_rawDescOnce.Do(func() {
		file_orderer_etcdraft_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderer_etcdraft_configuration_proto_rawDesc), len(file_orderer_etcdraft_configuration_proto_rawDesc)))
	})
	return file_orderer_etcdraft_configuration_proto_rawDescData
}

var file_orderer_etcdraft_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orderer_etcdraft_configuration_proto_goTypes = []any{
	(*ConfigMetadata)(nil), // 0: etcdraft.ConfigMetadata
	(*Consenter)(nil),      // 1: etcdraft.Consenter
	(*Options)(nil),        // 2: etcdraft.Options
}
var file_orderer_etcdraft_configuration_proto_depIdxs = []int32{
	1, // 0: etcdraft.ConfigMetadata.consenters:type_name -> etcdraft.Consenter
	2, // 1: etcdraft.ConfigMetadata.options:type_name -> etcdraft.Options
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orderer_etcdraft_configuration_proto_init() }
func file_orderer_etcdraft_configuration_proto_init() {
	if File_orderer_etcdraft_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderer_etcdraft_configuration_proto_rawDesc), len(file_orderer_etcdraft_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderer_etcdraft_configuration_proto_goTypes,
		DependencyIndexes: file_orderer_etcdraft_configuration_proto_depIdxs,
		MessageInfos:      file_orderer_etcdraft_configuration_proto_msgTypes,
	}.Build()
	File_orderer_etcdraft_configuration_proto = out.File
	file_orderer_etcdraft_configuration_proto_goTypes = nil
	file_orderer_etcdraft_configuration_proto_depIdxs = nil
}
