// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: orderer/etcdraft/metadata.proto

package etcdraft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockMetadata stores data used by the Raft OSNs when
// coordinating with each other, to be serialized into
// block meta dta field and used after failres and restarts.
type BlockMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maintains a mapping between the cluster's OSNs
	// and their Raft IDs.
	ConsenterIds []uint64 `protobuf:"varint,1,rep,packed,name=consenter_ids,json=consenterIds,proto3" json:"consenter_ids,omitempty"`
	// Carries the Raft ID value that will be assigned
	// to the next OSN that will join this cluster.
	NextConsenterId uint64 `protobuf:"varint,2,opt,name=next_consenter_id,json=nextConsenterId,proto3" json:"next_consenter_id,omitempty"`
	// Index of etcd/raft entry for current block.
	RaftIndex     uint64 `protobuf:"varint,3,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMetadata) Reset() {
	*x = BlockMetadata{}
	mi := &file_orderer_etcdraft_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMetadata) ProtoMessage() {}

func (x *BlockMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orderer_etcdraft_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMetadata.ProtoReflect.Descriptor instead.
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return file_orderer_etcdraft_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *BlockMetadata) GetConsenterIds() []uint64 {
	if x != nil {
		return x.ConsenterIds
	}
	return nil
}

func (x *BlockMetadata) GetNextConsenterId() uint64 {
	if x != nil {
		return x.NextConsenterId
	}
	return 0
}

func (x *BlockMetadata) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

// ClusterMetadata encapsulates metadata that is exchanged among cluster nodes
type ClusterMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates active nodes in cluster that are reacheable by Raft leader
	ActiveNodes   []uint64 `protobuf:"varint,1,rep,packed,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMetadata) Reset() {
	*x = ClusterMetadata{}
	mi := &file_orderer_etcdraft_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetadata) ProtoMessage() {}

func (x *ClusterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orderer_etcdraft_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetadata.ProtoReflect.Descriptor instead.
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return file_orderer_etcdraft_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterMetadata) GetActiveNodes() []uint64 {
	if x != nil {
		return x.ActiveNodes
	}
	return nil
}

var File_orderer_etcdraft_metadata_proto protoreflect.FileDescriptor

const file_orderer_etcdraft_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1forderer/etcdraft/metadata.proto\x12\betcdraft\"\x7f\n" +
	"\rBlockMetadata\x12#\n" +
	"\rconsenter_ids\x18\x01 \x03(\x04R\fconsenterIds\x12*\n" +
	"\x11next_consenter_id\x18\x02 \x01(\x04R\x0fnextConsenterId\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x03 \x01(\x04R\traftIndex\"4\n" +
	"\x0fClusterMetadata\x12!\n" +
	"\factive_nodes\x18\x01 \x03(\x04R\vactiveNodesBj\n" +
	".org.hyperledger.fabric.protos.orderer.etcdraftZ8github.com/hyperledger/fabric-protos-go/orderer/etcdraftb\x06proto3"

var (
	file_orderer_etcdraft_metadata_proto_rawDescOnce sync.Once
	file_orderer_etcdraft_metadata_proto_rawDescData []byte
)

func file_orderer_etcdraft_metadata_proto_rawDescGZIP() []byte {
	file_orderer_etcdraft_metadata_proto_rawDescOnce.Do(func() {
		file_orderer_etcdraft_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderer_etcdraft_metadata_proto_rawDesc), len(file_orderer_etcdraft_metadata_proto_rawDesc)))
	})
	return file_orderer_etcdraft_metadata_proto_rawDescData
}

var file_orderer_etcdraft_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orderer_etcdraft_metadata_proto_goTypes = []any{
	(*BlockMetadata)(nil),   // 0: etcdraft.BlockMetadata
	(*ClusterMetadata)(nil), // 1: etcdraft.ClusterMetadata
}
var file_orderer_etcdraft_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orderer_etcdraft_metadata_proto_init() }
func file_orderer_etcdraft_metadata_proto_init() {
	if File_orderer_etcdraft_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderer_etcdraft_metadata_proto_rawDesc), len(file_orderer_etcdraft_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderer_etcdraft_metadata_proto_goTypes,
		DependencyIndexes: file_orderer_etcdraft_metadata_proto_depIdxs,
		MessageInfos:      file_orderer_etcdraft_metadata_proto_msgTypes,
	}.Build()
	File_orderer_etcdraft_metadata_proto = out.File
	file_orderer_etcdraft_metadata_proto_goTypes = nil
	file_orderer_etcdraft_metadata_proto_depIdxs = nil
}
